### ISSUE TITLE
[text] Current lyrics line gets hidden under top shadow of the lyrics box

### ISSUE THREAD

**Issue by Gamesnic** [spicetify/spicetify-themes#1011]
**Prerequisites**
Before opening an issue, make sure

- [x] 1. You have the most recent `spicetify` version.
- [x] 2. Your Spotify version is compatible with the `spicetify` version you are using.
- [x] 3. You have the most recent version of the themes.
- [x] 4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
The currently active line highlighted in the Lyrics box is being at the very top of it and as such also hides partially under its shadow.

**To Reproduce**
1. Go to 'Now Playing'
2. Click on 'See Lyrics'
3. Scroll down to 'highlighted lyrics line'

**Expected behavior**
The highlighted line should be out of the shadow area, and at best vertically centered in the box.

**Screenshots**
![image](https://github.com/spicetify/spicetify-themes/assets/49643487/a721c84f-1319-40d8-bcd5-065cfa17fd07)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
Failed to load resource: the server responded with a status of 404 ()
extension.js:1 Initializing Spicetify Marketplace v0.8.5
extension.js:1 Loaded Marketplace extension
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
gew4-spclient.spotify.com/remote-config-resolver/v3/configuration:1     Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:29 provider:transport resolve error T Object
f @ vendor~xpui.js:29
index.html:1 Uncaught (in promise) T
fullScreen.js:10 marked(): mangle parameter is enabled by default, but is deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install https://www.npmjs.com/package/marked-mangle, or disable by setting `{mangle: false}`.
(anonymous) @ fullScreen.js:10
fullScreen.js:10 marked(): headerIds and headerPrefix parameters enabled by default, but are deprecated since version 5.0.0, and will be removed in the future. To clear this warning, install  https://www.npmjs.com/package/marked-gfm-heading-id, or disable by setting `{headerIds: false}`.
(anonymous) @ fullScreen.js:10
xpui.js:1 Uncaught (in promise) BadGatewayError: GET request to wg://artist/v1/3AkGIMk9xwDj4A5ttNBPiN/desktop?format=json failed with status code 502
    at l.onSuccess (xpui.js:1:2170149)
    at onSuccess (xpui.js:1:2169963)
vendor~xpui.js:29 Uncaught (in promise) TypeError: Request URL cannot be blank.
    at vendor~xpui.js:29:1399271
    at new Promise (<anonymous>)
    at le (vendor~xpui.js:29:1399135)
    at Module.ce (vendor~xpui.js:29:1400358)
    at vendor~xpui.js:29:1388914
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2170149)
    at onSuccess (xpui.js:1:2169963)
onError @ vendor~xpui.js:29
extension.js:1     GET https://raw.githubusercontent.com/3raxton/spicetify-custom-apps-and-extensions/main/manifest.json 404 (Not Found)
R @ extension.js:1
(anonymous) @ extension.js:1
(anonymous) @ extension.js:1
extension.js:1     GET https://raw.githubusercontent.com/TheRandomLabs/Scoop-Spotify/master/manifest.json 404 (Not Found)
```

**Specifics (please complete the following information):**
 - OS: Windows 11 22H2
 - Spotify for Windows (64 bit) 1.2.24.756.g7a7fc7f0
 - Spicetify v2.27.0
 - xpui_2023-11-06_1699279287548_7a7fc7f
 - text theme

**Comment by Gamesnic** [comment]
Hey @harbassan, thanks alot for trying to fix the issue, but I think it went it the wrong direction.
![image](https://github.com/spicetify/spicetify-themes/assets/49643487/a07e709b-e604-4134-a619-fcca975629c3)

**Comment by harbassan** [comment]
i made a mistake, we havent pushed the actual fix yet.
