### ISSUE TITLE
Cant change into the specific theme

### ISSUE THREAD

**Issue by AhanafMahmud** [spicetify/spicetify-themes#1016]
Hi i am trying to change the theme to Nightlight 
https://github.com/spicetify/spicetify-themes/tree/master/Nightlight
but It doesn't show up at the marketplace then i downloaded it using the git but then when i use this command 

$ spicetify config color_scheme Nightlight 

ik that its a mistake from my side but can u provide me the code which will help me set it up.

**Comment by harbassan** [comment]
`spicetify config current_theme Nightlight`
