### ISSUE TITLE
Dreary Borked? 

### ISSUE THREAD

**Issue by Soliprem** [spicetify/spicetify-themes#1023]
Dreary works, but looks quite different than the screenshots. Would probably need to be flagged out-of-date, alongside any other unmaintained themes

**Comment by harbassan** [comment]
The two out-of-date themes (Dreary and Matte) are already tagged on the spicetify marketplace, but on github there's no obvious way to do so, especially because most people just download the whole repo. Unless you want to edit the readme's which would be be better than nothing I suppose.
