### ISSUE TITLE
Many themes removed

### ISSUE THREAD

**Issue by Gitmaster511** [spicetify/spicetify-themes#1032]
Many themes that are in the https://github.com/spicetify/spicetify-themes/blob/master/THEMES.md#catppuccin-latte are removed from the download section. For example I can't download any catpuccin, nord or the White Theme

**Comment by harbassan** [comment]
all of the themes shown in THEMES.md are inside the repo, if you're talking about a 'scheme' for that theme then you have to toggle that using the spicetify-cli. The cmd is `spicetify config color_scheme <value>`. Each theme's readme shows the available color schemes for that particular theme.
