### ISSUE TITLE
Theme Dribbblish Issues

### ISSUE THREAD

**Issue by b-lanczz** [spicetify/spicetify-themes#1036]
![Screenshot 2024-02-16 151855](https://github.com/spicetify/spicetify-themes/assets/160215585/3f38046f-58a2-4f1d-a1ab-32f81151bd3f)
the lyrics from the beautiful lyrics extension isn't showing

**Comment by harbassan** [comment]
https://github.com/surfbryce/beautiful-lyrics/issues/291
