### ISSUE TITLE
Lyrics plus won't fetch lyrics after latest update

### ISSUE THREAD

**Issue by AboodeDaBOSS** [spicetify/spicetify-themes#1038]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version.
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
(Please paste here console logs or attach a screenshot)
```

**Specifics (please complete the following information):**
 - Spotify version [e.g. 1.1.10.546.ge08ef575]
 - Spicetify version [e.g. 1.1.0]
 - Theme name

**Comment by harbassan** [comment]
https://github.com/spicetify/spicetify-cli/issues/2844
