### ISSUE TITLE
Blossom

### ISSUE THREAD

**Issue by TecEash1** [spicetify/spicetify-themes#1039]
**Describe the bug**
Issue Resizing friend activity and playlist section (left and right bars)

**To Reproduce**
1.Try to resize them

**Expected behavior**
To be able to easily resize them 

**Screenshots**

**Specifics (please complete the following information):**
Spotify for Windows (64 bit)
1.2.32.997.g4c6498b6
Spicetify v2.33.1
xpui_2024-02-23_1708709925614_4c6498b
cef_121.3.15+g4d3b0b4+chromium-121.0.6167.184
Runtime: Alloy

- Theme name: Blossom

Additional Notes:

It appears that spotify has updated the way they handle these bars. There are no longer arrows to resize them there is instead a click and hold section. At least from the web app version and the version of spotify without the blossom theme

**Comment by Alt3rr** [comment]
I alsso have this bug

**Comment by NYCJames** [comment]
This also happens with Onepunch theme

**Comment by BitKovin** [comment]
also have this bug

**Comment by applepines101** [comment]
I also cannot resize anything with the latest version of Spicetify and the Blossom theme, other than the entire window.
