### ISSUE TITLE
[Sleek] Volume bar delay

### ISSUE THREAD

**Issue by Alt3rr** [spicetify/spicetify-themes#1040]
**Describe the bug**
The volume bar has delay when sliding

**To Reproduce**
1. slide volume bar
2. 
**Expected behavior**
Slide instantly without delay

**Specifics (please complete the following information):**
 - OS: [win10]
 - Spotify version [1.2.32.997.g4c6498b6]
 - Spicetify version [v2.33.1]
 - Sleek

**Comment by sansmoraxz** [comment]
It may not just be the theme, I have observed delays even with no theme applied.

**Comment by Alt3rr** [comment]
On my side it only happens with this theme

**Comment by ari-party** [comment]
https://github.com/spicetify/spicetify-themes/pull/1053
