### ISSUE TITLE
[Dribblish] A total mess

### ISSUE THREAD

**Issue by vitorpontesd** [spicetify/spicetify-themes#1046]
**Describe the bug**
When trying to use Dribblish base in a fresh Spotify and Spicetify installation, it the layout is completely messed up, with almost no functionality

**To Reproduce**
1. Install Spicetify and Spicetify Marketplace
2. Install Dribblish

**Expected behavior**
Dribblish properly works

**Screenshots**
![image](https://github.com/spicetify/spicetify-themes/assets/75731021/15a39cc9-26aa-47d7-b733-da983463e92b)

**Logs**
`console
![image](https://github.com/spicetify/spicetify-themes/assets/75731021/f37d3cab-c5d1-4825-8296-886997cd03fe)

**Specifics (please complete the following information):**
 - OS: Windows 11 build 22631.3296
 - Spotify version 1.2.33.1042.gg26c92729
 - Spicetify version 2.36.1
 - Dribblish

**Comment by harbassan** [comment]
Dribblish doesn't work with the new layout, and wont for some time. You can change layout by going into the experimental features and disabling `enableGlobalNavBar`.
