### ISSUE TITLE
[text] Artist and song name are misaligned and first letters are cut off

### ISSUE THREAD

**Issue by krolremizy** [spicetify/spicetify-themes#1047]
Describe the bug
Artist and song name are misaligned and first letters are cut off

To Reproduce
1. launch spotify with text theme installed
Expected behavior
artist and song name are fully shown

Specifics (please complete the following information):

OS: [win11]
Spotify version [1.2.13.661]
Spicetify version [v2.36.1]
text

![image](https://github.com/spicetify/spicetify-themes/assets/72271872/ad448b7e-570b-44f7-9336-cb299c5507cc)

**Comment by darkthemer** [comment]
The theme is incompatible with the Cover Ambience extension; it's not the theme itself that is broken.

**Comment by krolremizy** [comment]
Sadly the issue still occurs after uninstalling Cover Ambience extension.
![image](https://github.com/spicetify/spicetify-themes/assets/72271872/40c58256-4e2d-4785-bb85-07f6a7997c5f)

**Comment by krolremizy** [comment]
Okay, so when I hid the song cover that's in the left bottom corner, the text aligned correctly, but now I don't know how to get the image back 🤔

**Comment by harbassan** [comment]
What are you using to get the image on the left side there? If its like that by default, then you're running an older spotify version that the theme may not be compatable with.
