### ISSUE TITLE
Spicetify Marketplace Bug

### ISSUE THREAD

**Issue by angelmora2004** [spicetify/spicetify-themes#1063]
**Describe the bug**
I can't use Marketplace because a kind of black box appears and I can't browse the store.

**Screenshots**
![imagen_2024-05-08_225027473](https://github.com/spicetify/spicetify-themes/assets/105449326/1e0c5046-22bd-4ddd-b3e5-b22b73b04452)

**Specifics (please complete the following information):**
 - OS: Win 11
 - Spotify version: 1.2.36.959.g04bf500c
 - Spicetify version: 2.36.11
 - Theme name: Hazy / Base

**Comment by harbassan** [comment]
go to hazy repo.
