### ISSUE TITLE
StarryNight Theme looks extremely weird on my 3840x2160 monitor

### ISSUE THREAD

**Issue by Veran04** [spicetify/spicetify-themes#1072]
**Describe the bug**
![image](https://github.com/spicetify/spicetify-themes/assets/70385552/70b0cf53-ed43-41e9-8898-b5929ecb26ad)

The image attached above is how my spotify looks when applying the Theme. It is missing a lot of buttons such as "lyrics" and "now playing view" which randomly appear under the player on the bottom left.

**To Reproduce**
1. have a 3840x2160 monitor
2. Apply the StarryNight theme with any color scheme

**Expected behavior**
I would like to make mine look like the example images.

**Screenshots**
See above.

**Specifics (please complete the following information):**
 - OS: [e.g. iOS]: **Windows 11**
 - Spotify version [e.g. 1.1.10.546.ge08ef575]: **Latest**
 - Spicetify version [e.g. 1.1.0]: **Latest**
 - Theme name: **StarryNight**

**Comment by harbassan** [comment]
The theme doesnt support the new navbar ui. In experimental features, which you can access by clicking your profile icon, search navbar and disable `Show global nav bar with home button, search...` etc. Should fix it.

**Comment by Veran04** [comment]
Fixed it, thank you so much
