### ISSUE TITLE
The theme flow

### ISSUE THREAD

**Issue by 0lav8** [spicetify/spicetify-themes#1074]
![image](https://github.com/spicetify/spicetify-themes/assets/169065856/8c1ece7b-be7a-491d-a47e-bac4903f1bc6)

I've been trying everything to remove these theme as it's clearly glitching and not showing any screen but everytime i try something it just uninstalls spicetify. 

I just want to remove these theme and be able to use spicetify, can i please get a code that works on terminal to remove just the theme? 

My spicetify and macbook are both up to date

**Comment by aideyj** [comment]
Open Powershell and hit

spicetify enable-devtools

After that open Spotify

Open up DevTools by right clicking anywhere on Spotify, and then click on Inspect Element.

Click the Console tab in the DevTools window, paste the following command inside then execute

Marketplace.reset()

https://github.com/spicetify/spicetify-marketplace/wiki/Development

**Comment by 0lav8** [comment]
> Open Powershell and hit
> 
> 
> 
> spicetify enable-devtools
> 
> 
> 
> After that open Spotify
> 
> 
> 
> Open up DevTools by right clicking anywhere on Spotify, and then click on Inspect Element.
> 
> 
> 
> Click the Console tab in the DevTools window, paste the following command inside then execute
> 
> 
> 
> Marketplace.reset()
> 
> 
> 
> https://github.com/spicetify/spicetify-marketplace/wiki/Development
> 
> 

thank youu it worked
