### ISSUE TITLE
[Theme-name] dribbblish

### ISSUE THREAD

**Issue by schizoidcock** [spicetify/spicetify-themes#1076]
Why this theme look so weird after first installation??, i restarted spotify, uninstalled and still look weird there are missing instructions??

![image](https://github.com/spicetify/spicetify-themes/assets/6947240/141ba80d-0cd2-4874-bf65-ea0c89ec49cd)

**Comment by LetFiree** [comment]
It is the same for me

**Comment by wsandy1** [comment]
Also having this issue.

**Comment by obvRedwolf** [comment]
try disabling the new nav bar. you can disable this by clicking your profile, going into experimental features, then search "nav" and make sure "Show global nav bar with home button, search input and user avatar" is disabled/unchecked. it should look like this:
![image](https://github.com/spicetify/spicetify-themes/assets/71992659/0744588a-02fb-4ce2-a932-e25e96a92d35)

**Comment by Vyp3R** [comment]
Thanks @obvRedwolf, you are right on the money for fixing this weird display issue... however, the current version of Spotify seems to have a slight change to this option in _Experimental features_. It is no longer a tick box to enable or disable, but a drop-down selection list. With the options of `control`, `home-mext-to-navigation` and `home-next-to-search`. _(The last item looks to be the default.)_

![Screenshot1](https://github.com/spicetify/spicetify-themes/assets/607131/6912208e-6070-4cf3-a5c9-6056c796d7c3)

And it seems `control` is the one that needs to be selected. Once changed, Spotify will alter its appearance behind this _Experimental features_ dialogue - with greyed out options and blocked out text (see image below), as if the application has crashed or something.

![Screenshot2](https://github.com/spicetify/spicetify-themes/assets/607131/cbee9b3f-17de-461a-838d-5cdb0417828b)

It is not until you close the _Experimental features_ window, that another smaller dialogue box, previously hidden behind it, will be revealed. Simply stating: "Something went wrong. Try reloading the page" with a `Reload Page` button to press.

Once pressed, Spotify then refreshes, showing the Dribbblish theme correctly! Hooray!

**Note:** Dribbblish is the most obvious theme that suffers this display arrangement problem, but there are a few other Spicetify themes that also now display differently and so, more closely resembling their preview pictures.

**Comment by LetFiree** [comment]
Thanks, @obvRedwolf and @Vyp3R it is now working flawlessly

**Comment by Samuil1337** [comment]
Sorry for the necro post but I can't find the `Show global nav bar with home button, search input and user avatar` option anymore. Does somebody know where it got moved to or was it taken down for good? The theme would work flawlessly without changing it but I just like the old positions better.

**Comment by obvRedwolf** [comment]
The option isn't available anymore as the new nav bar is now the apart of the official UI and isn't an experimental option anymore.
