### ISSUE TITLE
[Theme-name]  Starry Night

### ISSUE THREAD

**Issue by Thensil** [spicetify/spicetify-themes#1079]
**Prerequisites**
Before opening an issue, make sure
Spicetify Version: v2.36.12
Spotify Version: 1.2.39.578.g0ea3f38b
Theme: StarryNight June 4 2024 Throught Market Place and Console Same Issue
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
Cut off display and over lapping Text
<img width="798" alt="image" src="https://github.com/spicetify/spicetify-themes/assets/64828620/567acd46-a31d-4f4e-b6e7-cad403bd0f9b">

<img width="800" alt="image" src="https://github.com/spicetify/spicetify-themes/assets/64828620/f1402094-6d31-41d7-982b-bd84651edc43">

**To Reproduce**

**Expected behavior**
Proper theme display

**Screenshots**

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
<img width="620" alt="image" src="https://github.com/spicetify/spicetify-themes/assets/64828620/a06e6351-2f42-4489-b0f1-416e4496e51f">
```

**Specifics (please complete the following information):**
 - OS: Windows x86
 - Spotify version 1.2.39.578.g0ea3f38b
 - Spicetify version v2.36.12
 - Theme name StarryNight

**Comment by rxri** [comment]
Starry Night is broken with Global Navbar. You need to revert to LibraryX UI.
1. Click on your avatar -> Experimental Features
2. Search for `global navbar`
3. Select `control`

**Comment by baolongdayyy** [comment]
I can't see the shooting stars on this theme.
