### ISSUE TITLE
StarryNight buttons

### ISSUE THREAD

**Issue by IMT07** [spicetify/spicetify-themes#1084]
Hi, with this theme (StarryNight), some buttons in apps and extensions are becomming unreadable. I tried it with a lot of other themes, and they all work, but with this theme it doesn't. One of the apps where it is unreadable is the Name that tune app, where the text on the buttons is just not showing. I think its because all the other themes I tried do not have such a complicated background and therefor they just make the button text the color of the background or smth but im not an expert. 
![image](https://github.com/spicetify/spicetify-themes/assets/81577133/4e6c60b5-363a-49a9-9a61-62ca2c97a0d9)

I'm using the latest version of spotify, spicetify and the theme.

**Comment by b-chen00** [comment]
Yes, this is probably due to the app taking certain color variables which either makes the text white on a white background or transparent. I'll take a look into this and adjust it.
