### ISSUE TITLE
StarryNight

### ISSUE THREAD

**Issue by CassandraCat** [spicetify/spicetify-themes#1094]
**Describe the bug**
When using Searh, a large black box appears at the bottom. Is it likely to be the playback progress bar?

**To Reproduce**
1. Go to 'Spotify'
2. Click on 'Search'

**Screenshots**
<img width="1792" alt="image" src="https://github.com/spicetify/spicetify-themes/assets/67346540/852a12d1-3feb-423f-a330-4ae6b4ded091">

**Specifics (please complete the following information):**
 - OS: macOS Sonoma 14.5
 - Spotify 1.2.41.434.g39a25e2c
 - Spicetify version 2.36.14

**Comment by harbassan** [comment]
This looks like its the advertisement placeholder box, if its bugging you there's a Spicetify plugin called "adblockify" which will remove it for you, along with any other ads :).

**Comment by CassandraCat** [comment]
> This looks like its the advertisement placeholder box, if its bugging you there's a Spicetify plugin called "adblockify" which will remove it for you, along with any other ads :).

thanks. solved
