### ISSUE TITLE
Feature Request: Nixos Integration 

### ISSUE THREAD

**Issue by sandptel** [spicetify/spicetify-themes#1096]
I was trying to setup spicetify themes on Nixos recently. And I feel that it is the perfect type of package that needs that nixos style integration to be able use it via home-manager.

**Comment by sandptel** [comment]
https://github.com/the-argus/spicetify-nix
It exist already. Maybe you guys should merge it with the main repository or provide more awarness about it.

**Comment by harbassan** [comment]
its third party (i didn't even know it existed) and we cant dedicate more time than we already do to something that's pretty niche. Its cool to see someone doing this though.

**Comment by sandptel** [comment]
It sure works very fine even being third-party maybe you can mention it in Readme somewhere with the tag third party ?
