### ISSUE TITLE
[Starry Night Base] 

### ISSUE THREAD

**Issue by Lunia974** [spicetify/spicetify-themes#1098]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version.
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
Whenever I have the lyrics opened and it tries to adjust itself, the top bar disappears and then it starts glitching up and down, not severely but noticeably.
 

**To Reproduce**
1. Go to "any song that uses spotify lyrics that updates"
2. Click on 'lyrics'
3. Scroll down to 'let it update naturally or click a lyrics further down'

**Expected behavior**
The bar top bar should not be disappearing or glitching up and down.

**Screenshots**
![image](https://github.com/user-attachments/assets/55ea8360-f46a-4960-b977-99bd372948d3)
![image](https://github.com/user-attachments/assets/0eeac4ca-403b-4b5d-80f7-fb2bfb58149e)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
![image](https://github.com/user-attachments/assets/af28bde7-9224-459f-92d3-75202591716a)
```

**Specifics (please complete the following information):**
 - OS: [Windows 11]
 - Spotify version [1.2.42.290.g242057a2]
 - Spicetify version [v2.36.15]
 - Starry Night Base

**Comment by sanoojes** [comment]
there is issuw in both global nav and normal control nav

https://github.com/user-attachments/assets/9a9936c9-184f-4dd6-a0f1-03488341f151

translating to top causes the issue

**Comment by sanoojes** [comment]
found out the issue i will be adding a pr soon after i test it out
