### ISSUE TITLE
[text] Songs not loading when scrolling down on playlist.

### ISSUE THREAD

**Issue by Padster737** [spicetify/spicetify-themes#1102]
**Describe the bug**
Some songs not showing until I scroll down in the playlist. Happens in every playlist.

**To Reproduce**
1. Go to any playlist on Spotify
2. Scroll down on the playlist
3. See error

**Expected behavior**
I expected all songs to load, like they do when using any other theme or not using Spicetify.

**Screenshots**

<img width="1440" alt="Screenshot 2024-08-05 at 21 03 50" src="https://github.com/user-attachments/assets/dae400b3-f825-4e22-a065-ea6711741fc0">

<img width="1440" alt="Screenshot 2024-08-05 at 21 04 14" src="https://github.com/user-attachments/assets/b96ae2bb-a00c-4e5c-be6b-76d59aa4bdc1">

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
(Please paste here console logs or attach a screenshot)
```

**Specifics (please complete the following information):**
 - OS: MacOS 15.0
 - Spotify version: 1.2.43.420.gc7b23f70
 - Spicetify version: 2.36.15
 - Theme name: Text (Nord)

**Comment by ericlovesmath** [comment]
I can't reproduce the issue with Text Nord on MacOS 14.6, it loads fine on my end. Does this happen with all `text` themes or just nord? Do you have the logs? It feels more likely that it might just be Spotify itself failing to fetch the playlist for whatever reason.

**Comment by xavierhayesmuth** [comment]
I had this problem too. After re-installing Spotify and reapplying spicetify my playlists came back.

**Comment by Padster737** [comment]
How to get logs?

Also @xavierhayesmuth my playlists are there it's just I can't see all the songs unless I scroll down far enough.

**Comment by ericlovesmath** [comment]
> How to get logs?

Its in the bottom of the issue you submitted

**Comment by Padster737** [comment]
So do I hit `Ctrl + Shift + I` on Chrome, Terminal or Spotify?

**Comment by xavierhayesmuth** [comment]
> How to get logs?
> 
> Also @xavierhayesmuth my playlists are there it's just I can't see all the songs unless I scroll down far enough.

Yeah, that's what I meant, sorry. My playlists were there as well but I couldn't see any songs. Re-installing as I said and re-applying spicetify sorted it out.

**Comment by Padster737** [comment]
I tried that and it didn't work, I still have the same problem.

**Comment by sanoojes** [comment]
make view as to compact it will solve the issue 
![image](https://github.com/user-attachments/assets/353bb731-895c-416b-bad7-ff985b9e5fb6)

**Comment by Padster737** [comment]
That worked, thanks.
