### ISSUE TITLE
I can't change the color sheme

### ISSUE THREAD

**Issue by SladeTHR** [spicetify/spicetify-themes#1104]
At first I tried to change the color scheme of the Sleek theme and absolutely nothing changed. Then I found this page on GitHub and tried to change the theme to Sleek, and strangely Powershell started writing that such a theme does not exist. As a result, now this message is constantly displayed on my screen and I can't even try to change the color scheme.
![image](https://github.com/user-attachments/assets/7efb6f8a-00c4-40f6-a4b4-005d8599d840)

**Comment by SladeTHR** [comment]
You need to specify "marketplace" or "SpicetifyDefault" as the theme, but now I just can't change the color scheme. I want to try the green "Deep" scheme in the "Sleek" theme, but the scheme remains "Wealthy". What am I doing wrong?

![image](https://github.com/user-attachments/assets/0a0cb10a-a704-493a-b6ee-f19319dc4d3a)

**Comment by SladeTHR** [comment]
As I understand it, you can't change the color scheme in themes that you downloaded from the Marketplace, so I had to download these themes from GitHub and move it to AppData\Roaming\spicetify\Themes. I don't really understand why the Marketplace is needed at all, if there is no possibility of changing the color scheme...

**Comment by harbassan** [comment]
> As I understand it, you can't change the color scheme in themes that you downloaded from the Marketplace

You can, in marketplace theres a dropdown on the top right (where it says "wealthy")
![image](https://github.com/user-attachments/assets/99cf950a-55c8-457d-ac77-2e7586d44cd3)
