### ISSUE TITLE
StarryNight Galaxy Variant UI is broken after latest spotify update (extensions broke too)

### ISSUE THREAD

**Issue by Veran04** [spicetify/spicetify-themes#1113]
**Describe the bug**
After the most recent spotify update causing my UI to break, I did the same steps I usually take which are:

1. Open command line
2. type "spicetify update"
Typically this is all I have to do and then my theme is reapplied. However in this case, the theme was applied in a very buggy way. You can see in the attached image that the panel on the right hand side (now playing view) takes up half the screen, and the bar you would typically drag to resize this does not work. I also get an error about needing to run the command spicetify sidebar_config 0 so I tried that and reapplied which made me stop receiving the error message but did not fix any of the UI issues. My extensions (shuffle+) are also not working currently.

**To Reproduce**
See above

**Expected behavior**
The theme will allow me to resize the view on the right hand side normally, and the shuffle+ extension will work again

**Screenshots**
![{095BA4D1-605B-4A1E-B9C0-871015086070}](https://github.com/user-attachments/assets/5ff83c6f-7130-4823-b2fb-e390dcc5abbe)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
index.html:1 document.domain mutation is ignored because the surrounding agent cluster is origin-keyed.
(anonymous) @ index.html:1
CircularSp-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSp-Book.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Bold.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
CircularSpTitle-Black.woff2:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:453 [spicetifyWrapper] Waiting for required webpack modules to load
4151.css:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
favicon.ico:1 
        
        
       Failed to load resource: net::ERR_NAME_NOT_RESOLVED
spicetifyWrapper.js:474 [spicetifyWrapper] All required webpack modules loaded
theme.js:88 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at theme.js:88:16
    at waitForElement (theme.js:4:5)
extension.js:8 Initializing Spicetify Marketplace v1.0.2
extension.js:8 Loaded Marketplace extension
gue1-spclient.spotify.com/remote-config-resolver/v3/configuration:1 
        
        
       Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:1 provider:transport resolve error e Object
g @ vendor~xpui.js:1
index.html:1 Uncaught (in promise) e
8The resource <URL> was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally.
```

**Specifics (please complete the following information):**
 - OS: Windows 11
 - Spotify version Latest
 - Spicetify version 2.38.3
 - Theme name: Starry Night Galaxy Variant

**Comment by Veran04** [comment]
Shuffle+ is now working again after the latest Spicetify update (2.38.4) but my theme is still broken (cant resize right hand panel, cant access the home button, no search bar at the top)

**Comment by b-chen00** [comment]
Do you have any other installed snippets or extensions? I see the issue with the right hand panel which works only when the "Now playing view" is open. I will find a better solution for that but I am not able to replicate the missing home button and search bar.

**Comment by Veran04** [comment]
How would I view my installed snippets/extensions? Normally I'd click the marketplace button at the upper left but I am not seeing that either as part of this issue. Should I try reinstalling the theme?

**Comment by Veran04** [comment]
May be also worth nothing that it is running even worse as of this morning despite me making no changes. Upon opening spotify I am now greeted with a very long black screen and songs are taking a considerably long time to load

**Comment by b-chen00** [comment]
The theme shouldn't have made the marketplace button + top bar disappear as it doesn't touch that part of the Spotify client. 

I noticed how there is an error message in your screenshot. Try the command and see if that fixes it.
![image](https://github.com/user-attachments/assets/20070673-2c2b-4fc1-afed-26ee5f76f71b)
 
For this issue and the other issues you noticed, they're most likely not due to the theme as the theme doesn't directly affect those part of the client. I would point you to the Spicetify discord to see if there was a similar problem or potentially a solution.

However, the resizing problem is definitely due to the theme and I will be working on a fix for that though.

**Comment by Veran04** [comment]
I tried running that command, it didn't change anything unfortunately. I also tried making a post on the main spotify-cli issues page and it got deleted with a comment saying it's a theme issue, but you're saying it's not a theme issue so I am confused on where to proceed.
thank you again for being so patient with me and helping cause I really love the theme and spicetify and wanna keep using it

**Comment by b-chen00** [comment]
Interesting, are you able to switch to a different theme? My suggestion right now is to remove the StarryNight theme in order to see if the navbar comes back. You could also try to reset experimental features. 

![image](https://github.com/user-attachments/assets/effdf713-2a74-4ec2-b5f8-dc116f8d2ddc)

If you are proficient with css or using the inspect tool, you can try to see what is happening to the global navbar element using spicetify enable-devtools

![image](https://github.com/user-attachments/assets/fb205196-b844-4137-84ef-f44c8da735e5)


Also don't worry about it, I just hope I can be of help

**Comment by Veran04** [comment]
Gonna give this all a shot tonight when I get home or at the latest tomorrow afternoon after work and then I will get back to you with how it goes - thanks again man

**Comment by Veran04** [comment]
![{E8C8F3A1-10A9-44C3-950A-34CB12528DAF}](https://github.com/user-attachments/assets/aa8dd35d-7b99-411a-a38c-7d73925077b5)
It seems like it is indeed a theme issue as everything looks fine after running "spicetify restore" to set things back to defaults. Any suggestions on how to proceed? Do I need to pull an updated version of the theme, I havent done that in a while not sure if it is automatic

**Comment by b-chen00** [comment]
"spicetify restore" removes everything including Spicetify itself and brings you back to normal Spotify so there isn't much to go off of that alone. Version of theme should be automatic. See if there's any extension installed in your config-xpui.ini file at the line "extensions" which can be found in 

![image](https://github.com/user-attachments/assets/30a63fb7-256b-403e-86a2-db4f9791cb82)

Other than that try to reset your experimental features as shown above

**Comment by b-chen00** [comment]
If you want to remove the StarryNight theme and see if it is causing the issue you can delete it by 

running "spicetify enable-devtools",
right clicking the client
click show devtools
navigate to the Application tab into the local storage tab on the left 
delete all the values when searching for StarryNight

![image](https://github.com/user-attachments/assets/2aeca71f-e55b-4966-b928-1b1f7e018982)

**Comment by Veran04** [comment]
![{F5A749DB-5DD7-4DC8-B76C-CFB41424019F}](https://github.com/user-attachments/assets/10900d9e-6a59-4645-b0d7-959279bfe491)
Extensions appears to be blank when running "spicetify config" and viewing the file through terminal.
I verified by manually opening the file inside appdata with notepad as well and it is blank


I haven't been able to access that experimental features button from your screenshot since my profile icon is hidden by the bug and it seems like that is what you're clicking to access that.

Is there a way to backup my settings before I uninstall and reinstall? I assume "spicetify backup" does this and then I will run "spicetify backup restore": after reinstalling but just want to verify before I proceed with the uninstall to make sure I dont mess things up.

My discord is veran99 if you do want to add me there, but please don't feel obligated to do so

thanks a ton again

**Comment by b-chen00** [comment]
You should be safe to uninstall and reinstall. Not too familiar with the backup commands myself as I don't use them when I reinstall which hasn't affected me so far. But, yea I think the commands are "spicetify backup" and "spicetify restore backup".

**Comment by b-chen00** [comment]
Will try to set up a call

**Comment by Veran04** [comment]
Resolved over a discord call with Brandon - If anyone else encounters this issue, the fix was to manually redownload the spicetify-themes repo and overwrite my installation with latest
