### ISSUE TITLE
[Ziro, Sleek, probably others] Now playing view's gradient is broken 

### ISSUE THREAD

**Issue by kaizjen** [spicetify/spicetify-themes#1116]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version.
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
The gradient is incorrectly applied on the now playing view (looks like there are two gradients??)

**To Reproduce**
1. Open "Now playing" view

**Screenshots**
![this fade to darker](https://github.com/user-attachments/assets/a9135f5c-c775-428f-9f81-19e4f72a7bc5)

**Logs**
Irrelevant, can provide if necessary

**Specifics (please complete the following information):**
 - OS: Windows
 - Spotify version: 1.2.47.364.gf06e5cee
 - Spicetify version v2.38.4
 - Themes affected: Ziro, Sleek, and probably others

**Comment by kaizjen** [comment]
I found that it's this `:before` element that's causing weird gradient issues. If you remove its background, the issues disappear, however, sometimes the text may not be legible - this is the before element:
![::before](https://github.com/user-attachments/assets/692646c9-d0f8-4bd4-8fbf-e93f366d3d37)
(selector: `#Desktop_PanelContainer_Id > div > div.cZCuJDjrGA2QMXja_Sua > div:nth-child(2) > div > div > div.main-nowPlayingView-nowPlayingWidget > div > div.main-nowPlayingView-contextItemInfo::before`)

CSS kinda sucks

**Comment by kaizjen** [comment]
I disabled themes and this thing is still there (not on the web version), so I think I've been selected for one of Spotify UI experiments, unless Spicetify itself somehow causes this.

**Comment by ItsEpicBeast** [comment]
@kaizjen How do I get access to the dev tools? I thought with the recent updates it would have been fixed by now but I must try this fix
