### ISSUE TITLE
Add Controls to Minimize/Close as part of the theme

### ISSUE THREAD

**Issue by kstelakis** [spicetify/spicetify-themes#296]
I know I can use the normal ones but they look ugly and out of place. the no controls looks better but well it has no controls.
I dont know if its even possible but some icons put as part of the theme would be cool. smt like this, ty.
![Screenshot_118](https://user-images.githubusercontent.com/19624186/112126445-2299e680-8bcd-11eb-9a02-4d906ea065b9.png)

**Comment by ArashMaghsoodi** [comment]
I DAMENLY AGREE! It would be great if they add this.

**Comment by baszin** [comment]
I agree, Windows one aren't good with these themes and the NoControl makes closing and resizing more difficult

**Comment by 23Chromosomes** [comment]
How do you even disable the control to start with?

**Comment by m4racz** [comment]
on Windows 10, you can try this: https://github.com/morpheusthewhite/spicetify-themes/blob/master/Dribbblish/SpotifyNoControl.exe

Since new version of UI, this works for me only if I run spotify with flag  --transparent-window-controls

**Comment by afonsojramos** [comment]
I know this is something that everyone wants, but, at the moment, this is still not possible. Therefore I will close this.
