### ISSUE TITLE
Ziro Purple-Light: White text against light background.

### ISSUE THREAD

**Issue by LyNac** [spicetify/spicetify-themes#542]
Loving the Light Purple Ziro theme, but the white text and search icon is barely visible against the light background. (I tweaked the scrollbar color to make it more visible for myself, not sure which property changes the white text.)

![Ziro-Light-Purple-Text-Issue](https://user-images.githubusercontent.com/30939927/134583607-396e28ec-5045-4684-a9cf-152e810448d0.png)

**Comment by morpheusthewhite** [comment]
@schnensch0

**Comment by oatnoodles** [comment]
also looking for a fix to this. is there a setting that's doing this? it also does it on the spicetify default theme.

**Comment by morpheusthewhite** [comment]
I think last PR should have fixed it. Please update the theme and check again

**Comment by oatnoodles** [comment]
i just downloaded the file and the problem still persists (both on purple-light and orange-light.)

**Comment by afonsojramos** [comment]
Closing this as it was fixed in #614.
