### ISSUE TITLE
SpotifyNoControl Still Showing Windows Control

### ISSUE THREAD

**Issue by Fauzaan** [spicetify/spicetify-themes#546]
**Describe the bug**
Launching Spotify with 'SpotifyNoControl.exe' doesn't remove the controls right after.

**To Reproduce**
1. Pinned SpotifyNoControl.exe to taskbar
2. Try opening spotify with SpotifyNoControl.exe

**Expected behavior**
SpotifyNoControl.exe launches Spotify and removes controls right after

**Screenshots**
![SpotifyNoControlShowingWindows](https://user-images.githubusercontent.com/9331023/134804734-1988e0a3-6512-4da8-a261-f1903218ab90.png)

**Logs**

Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

![SpotifyNoControlConsoleLog](https://user-images.githubusercontent.com/9331023/134804802-b14fbfbe-c05f-484b-a7e2-c9dfd7c6bd0e.png)

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify for Windows 1.1.68.632.g2b11de83
 - Spicetify version 2.6.6
 - Dribblish

**Tried SpotifyNoControl from the _Extra and from here : https://github.com/morpheusthewhite/spicetify-themes/blob/master/_Extra/SpotifyNoControl/README.md still showing the Windows Control

**Comment by hewnly** [comment]
can confirm the same issue at the lastest version

**Comment by morpheusthewhite** [comment]
Can you try to use the alternatives (https://github.com/morpheusthewhite/spicetify-themes/tree/master/_Extra/SpotifyNoControl#alternatives)?

**Comment by Fauzaan** [comment]
@morpheusthewhite i did use both of the alternatives but AHK implementation no longer work as mention on readme

**Comment by pWoLiAn** [comment]
![image](https://user-images.githubusercontent.com/49567139/135806320-961e1650-624b-4068-b56b-4a0a29e925d0.png)

Can confirm the same on Dribblish with latest spicetify and spotify version Spotify for Win32
1.1.69.612.gb7409abc

Something else I noted is that the terminal stays open without exiting when running the executable

**Comment by hewnly** [comment]
yes!! something along the lines of "failed to execute shortcut file", using julienmallie's executable it gave me this error but the alternatives AHK didn't launch a terminal at all...

**Comment by LucasZhao22** [comment]
can confirm the same issue at the latest version (specifics: Spotify for Windows 1.1.72.439.gc253025e)

**Comment by DroidZed** [comment]
Any updates ? The controls annoy me :(

**Comment by afonsojramos** [comment]
At the moment, there is no way of having this not show up, therefore I will close this issue.
