### ISSUE TITLE
FLUENT: White Play button

### ISSUE THREAD

**Issue by Krappa420** [spicetify/spicetify-themes#561]
****Describe the bug**
White Play button using Fluent skin

**To Reproduce**
1. Open spotify
2. See the play button is white

**Screenshots**
![image](https://user-images.githubusercontent.com/66475753/136037785-2269eb89-be02-407c-94a2-7fc9c1a42382.png)

**Specifics:**
 - OS: Windows 10 21H1 / 19043.1266
 - Spotify version: 1.1.69.612.gb7409abc
 - Spicetify version: 2.7
 - Theme name: Fluent (Latest Version)

I even cleared backup, redownloaded the theme file, etc. Same issue**

**Comment by williamckha** [comment]
Could you provide logs from console?

**Comment by Krappa420** [comment]
Where can I find these logs? 

@williamckha

**Comment by Rauvagol** [comment]
same issue here, only using fluent and the hide-podcasts 
![image](https://user-images.githubusercontent.com/7938335/137406246-9e349f55-0058-4d54-ada4-da82985e769d.png)

**Comment by afonsojramos** [comment]
Is this still happening @Krappa420 ?
