### ISSUE TITLE
[Dribbblish] Left side-panel resizing feature is not working

### ISSUE THREAD

**Issue by Xanaxus** [spicetify/spicetify-themes#565]
**Describe the bug**
The resizing feature not working 

**To Reproduce**
- install the themes via the AUR
- Install the dribblish theme
- apply the changes

**Expected behavior**
Only the icons needs to be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/53279068/136646704-36708000-dcb1-4278-a089-6383fc885b21.png)

**Logs** 
![image](https://user-images.githubusercontent.com/53279068/136647461-5572bb6e-ec8d-4d66-8974-372b30b1b913.png)
![image](https://user-images.githubusercontent.com/53279068/136647479-2a95d7a6-c455-4fc8-9d34-f4dde471d44a.png)

```
vendor~xpui.js:1 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2353172)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2355454)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2048746
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2595327)
    at As (https://xpui.app.spotify.com/vendor~xpui.js:29:2619179)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2618958)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2603729)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2602651)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2565107
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2793496)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564835)
    at yi (https://xpui.app.spotify.com/vendor~xpui.js:29:2565052)
    at vi (https://xpui.app.spotify.com/vendor~xpui.js:29:2564987)
    at Es (https://xpui.app.spotify.com/vendor~xpui.js:29:2603150)
    at rl (https://xpui.app.spotify.com/vendor~xpui.js:29:2629563)
    at render (https://xpui.app.spotify.com/vendor~xpui.js:29:2632674)
    at https://xpui.app.spotify.com/xpui.js:1:1034344
(anonymous) @ vendor~xpui.js:1
xpui.js:1 Uncaught (in promise) Error: PUT request to sp://ads/v1/slots/stream failed with status code 500
    at l.onSuccess (xpui.js:1)
    at onSuccess (xpui.js:1)
vendor~xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
homeConfig.js:83 Uncaught TypeError: Cannot read property '0' of undefined
    at homeConfig.js:83
    at Array.forEach (<anonymous>)
    at injectInteraction (homeConfig.js:83)
    at homeConfig.js:163
    at Item.onClick (spicetifyWrapper.js:590)
    at HTMLLIElement.item._element.onclick (spicetifyWrapper.js:578)
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/644.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/22.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/754.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/service-worker.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Specifics (please complete the following information):**
 - OS: Arch based Linux: OBARUN
 - Spotify version : 1.1.68.632.g2b11de83
 - Spicetify version : DEV (installed via yay: choose the git version
 - Theme name : Dribbblish

**Comment by Xanaxus** [comment]
Ok I tried the spicetify-cli only version, but then also having the same issue.

**Comment by khanhas** [comment]
Please upgrade everything to the latest (Spotify, spicetify and dribbblish theme) and see if there is still any problem.

**Comment by Xanaxus** [comment]
hey I just did a fresh install on fedora 35 and I am still facing the same issues

**Comment by ProXeN** [comment]
Having the same issue.

**Comment by InfoFreak-13** [comment]
Any workaround for this issue?

**Comment by afonsojramos** [comment]
Is this still happening @InfoFreak-13 @ProXeN @Xanaxus?

**Comment by Xanaxus** [comment]
yes but for now I am just resizing the sidebar

**Comment by erfan1389** [comment]
> Yes, I am still facing this issue
> 
> But for now, I am just resizing the sidebar manually.

Hi there, I am having the same issue. Could you please tell me how you resize the sidebar manually? I am very new to all of this. Thanks a lot in advance.

**Comment by Xanaxus** [comment]
Its the same as you normally resize the window; so get mouse on the side-panel right border, and then move it to the left to ur desirability

**Comment by erfan1389** [comment]
> Its the same as you normally resize the window; so get mouse on the side-panel right border, and then move it to the left to ur desirability 

Yeah but my issue is that does not work. Nothing happens when I do that

**Comment by Vehzx** [comment]
also have this issue

**Comment by Xanaxus** [comment]
> > Its the same as you normally resize the window; so get mouse on the side-panel right border, and then move it to the left to ur desirability
> 
> Yeah but my issue is that does not work. Nothing happens when I do that

Hmm actually I stopped using spotify and have started using apple music so when I start to use spotify I will send u a video if posible on how I was able to do it

**Comment by Xanaxus** [comment]
> > Its the same as you normally resize the window; so get mouse on the side-panel right border, and then move it to the left to ur desirability
> 
> Yeah but my issue is that does not work. Nothing happens when I do that

Hmm..... actually, I stopped using Spotify and have started using Apple Music. So when I start to use Spotify I will send u a video if possible on how I was able to do it.

**Comment by cumw** [comment]
> > Its the same as you normally resize the window; so get mouse on the side-panel right border, and then move it to the left to ur desirability
> 
> Yeah but my issue is that does not work. Nothing happens when I do that

Its because the dribbblish.js extension is not in the extensions folder it fixed the issue for me when i manually copied the dribbblish.js filed from ~/Themes/Dribbblish folder and pasted in the extensions folder
