### ISSUE TITLE
[Fluent] Artist on friend activity bugged

### ISSUE THREAD

**Issue by nanchaara** [spicetify/spicetify-themes#599]
**Describe the bug**
Artist on friend activity bugged.

**Screenshots**
![image](https://user-images.githubusercontent.com/71387731/140507833-d6cc5773-72ab-4b78-9319-f371b4323b1e.png)

**Specifics (please complete the following information):**
 - OS: Windows 11 (Latest)
 - Spotify version 2.7.2
 - Spicetify version 1.1.71.560.gc21c3367
 - Fluent

**Comment by UmerF** [comment]
Same issue here.

**Comment by nanchaara** [comment]
found another css bug, 
![image](https://user-images.githubusercontent.com/71387731/141615420-167a21d3-5d84-424c-8bd3-9f8d006ca64d.png)

**Comment by afonsojramos** [comment]
Is this still happening @nanchaara?

**Comment by nanchaara** [comment]
sorry for late response,
yes it's still happening
both bug 
![image](https://user-images.githubusercontent.com/71387731/157058079-4ad43578-09f1-4a26-96f9-4066a9d20265.png)
![image](https://user-images.githubusercontent.com/71387731/157058112-3d08afed-d16b-4170-b625-35126239b052.png)

**Comment by nanchaara** [comment]
any update on this bug? @afonsojramos 
the other one has been fixed
![image](https://user-images.githubusercontent.com/71387731/161433577-822329a3-805c-4844-983d-826acaccf9f6.png)

**Comment by afonsojramos** [comment]
Fluent is now being developed [here](https://github.com/williamckha/spicetify-fluent/). Thank you!
