### ISSUE TITLE
Dribbblish UI bug

### ISSUE THREAD

**Issue by jitterdev** [spicetify/spicetify-themes#609]
![image](https://user-images.githubusercontent.com/64605731/141656441-c16a0ded-9801-4992-88eb-6cfefaacab5f.png)

![image](https://user-images.githubusercontent.com/64605731/141656466-39558adb-9a53-4b4f-941e-4e9589cf1018.png)

Does not occur on https://github.com/JulienMaille/dribbblish-dynamic-theme.

**Comment by khanhas** [comment]
Are you sure you are using Dribbblish downloaded from here?
There is no "Dribbblish Setting" in this version so it couldn't possibly add menu on your layout like that.

**Comment by HuyHung1408** [comment]
reinstall Spicetify, then download the Dribbblish theme again, as far as I know, the big banner at the top is the Dribbblish Dynamic theme and when you apply the Dribbblish theme from here, the Dribbblish Dynamic theme remains. Make sure to uninstall the Dribbblish Dynamic theme correctly and try again. 
`Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/JulienMaille/dribbblish-dynamic-theme/master/uninstall.ps1" | Invoke-Expression`
