### ISSUE TITLE
Fluent sidebar bug with folders

### ISSUE THREAD

**Issue by Zento1917** [spicetify/spicetify-themes#612]
**Describe the bug**
The width limit cuts off anything within an expanded folder

**To Reproduce**
1. Create a playlist folder
2. Put a playlist in it
3. Expand the folder

**Expected behavior**
Extend the max width to accommodate the expanded folder tree or let user expand the sidebar (like how default Spotify deals with folders)

**Screenshots**
With multiple nested folders:
![image](https://user-images.githubusercontent.com/77404988/142155401-16f70736-a7cd-4c8f-8a29-6fbd1c4fb956.png)

With a single folder:
![image](https://user-images.githubusercontent.com/77404988/142155441-5792a417-d560-46b9-8728-ceec5f6f2891.png)

Example of how a playlist cover image (for reference to how they were cut off):
![image](https://user-images.githubusercontent.com/77404988/142155499-e3a84e7d-19fe-4c85-aeb5-833623c7af4b.png)

**Logs**
![image](https://user-images.githubusercontent.com/77404988/142154653-7280b0ff-2f5a-4433-8619-3eb92695b2a3.png)

**Specifics:**
 - OS: Windows 10 Pro
 - Spotify version 1.1.72.439.gc253025e
 - Spicetify version 2.8.1
 - Fluent (dark)

**Comment by sagars007** [comment]
@Zento1917 
This might be helpful :)
_Originally posted by @sagars007 in https://github.com/morpheusthewhite/spicetify-themes/issues/574#issuecomment-983352637_

**Comment by kyrie25** [comment]
Theme no longer maintained in this repo, closing issue.
