### ISSUE TITLE
[Fluent] Sidebar Playlist icons bug

### ISSUE THREAD

**Issue by CyberNiinja** [spicetify/spicetify-themes#613]
**Describe the bug**
When Scrolling down in the sidebar, the Playlist Pictures disappear.
Maybe something similar to #567?

**To Reproduce**
1. Start spotify.
2. Scroll down to the bottom in the left sidebar with the playlists
3. Scroll up to to the top again
4. All the playlist icons that were scrolled "under" the Liked Songs, now have no icons.

**Expected behavior**
When scrolling down and up again, the playlist icons don't change at all.

**Screenshots**
Step 1 - Before: 
![image](https://user-images.githubusercontent.com/23138050/142180950-a107a992-29cc-4098-9729-02785f3f857a.png)

Step 2 - Scroll down: 
![image](https://user-images.githubusercontent.com/23138050/142181061-6810dd8f-16d0-4fe4-9161-1652425c52e4.png)

Step 3 - Scroll up again:
![image](https://user-images.githubusercontent.com/23138050/142181126-fd6a31a8-c507-491b-9b17-5731c0e0487e.png)

**Logs**
```
fluent.js:77 Uncaught TypeError: Cannot read properties of undefined (reading 'Translations')
    at fluent.js:77
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2492684)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2495268)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2135437
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2730563)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2754295)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:2967887)
    at hi (https://xpui.app.spotify.com/vendor~xpui.js:29:2700099)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2754074)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2738953)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2737875)
c @ vendor~xpui.js:29
xpui.js:1 cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/644.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-routes-homepage-takeover-ad.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/596.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-home.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Specifics**
 - OS: [Windows 11 Ver. 10.0.22499 Buiild 22499]
 - Spotify version [1.1.72.439.gc253025e]
 - Spicetify version [2.8.1]
 - Fluent

**Comment by williamckha** [comment]
Did you follow all installation instructions?
For the sidebar playlists to show properly, ensure that these two lines are added in the Patch section of your config-xpui.ini file:
```ini
[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,

**Comment by Libror** [comment]
> Did you follow all installation instructions? For the sidebar playlists to show properly, ensure that these two lines are added in the Patch section of your config-xpui.ini file:
> 
> ```ini
> [Patch]
> xpui.js_find_8008 = ,(\w+=)32,
> xpui.js_repl_8008 = ,${1}56,
> ```

I still have the same problem after adding the two lines.

**Comment by CyberNiinja** [comment]
> Did you follow all installation instructions? For the sidebar playlists to show properly, ensure that these two lines are added in the Patch section of your config-xpui.ini file:
> 
> ```ini
> [Patch]
> xpui.js_find_8008 = ,(\w+=)32,
> xpui.js_repl_8008 = ,${1}56,
> ```

yeah, I redownloaded and installed everything before writing the bug report. 
I hadn't put the patches, before but I also still have the problem after adding them. 
Log output hasnt changed either...

**Comment by UmerF** [comment]
Any fix to this? My Spotify just updated and now all the icons are gone, doesn't matter of I scroll down or not.

**Comment by stefanw1337** [comment]
Lines were in there already for me, but I also are getting no icons, rather "error" icons than no icons:
https://i.postimg.cc/qqdJtWP7/image.png

**Comment by williamckha** [comment]
You must disable dribblish.js if you have enabled it in config

**Comment by stefanw1337** [comment]
Isn't that uninstalling the theme? lol, quite opposite of what I'm trying to do!
________________________________

**Comment by williamckha** [comment]
Are you using Fluent theme or Dribblish?

**Comment by stefanw1337** [comment]
Dribbblish with Nord-Dark theme

**Comment by CyberNiinja** [comment]
> Dribbblish with Nord-Dark theme

This is an issue that concerns the fluent theme :)

**Comment by williamckha** [comment]
Not sure what is causing this issue, can you try increasing the timeout in fluent.js like shown: https://github.com/williamckha/spicetify-fluent/commit/4e02067268b1c876f4f3e5df49d0448ded663227 and see if it fixes the issue?
Or you can try reinstalling Fluent from my repo https://github.com/williamckha/spicetify-fluent/

**Comment by UmerF** [comment]
> Not sure what is causing this issue, can you try increasing the timeout in fluent.js like shown: [williamckha/spicetify-fluent@4e02067](https://github.com/williamckha/spicetify-fluent/commit/4e02067268b1c876f4f3e5df49d0448ded663227) and see if it fixes the issue? Or you can try reinstalling Fluent from my repo https://github.com/williamckha/spicetify-fluent/

Long shot, but just confirming. My Spicetify version is upgraded and it's 2.8.2, and your repo mentions 2.7.0 — is that just an old edit, or it's meant to only work on that Spicetify version?

Thanks.

**Comment by williamckha** [comment]
> Long shot, but just confirming. My Spicetify version is upgraded and it's 2.8.2, and your repo mentions 2.7.0 — is that just an old edit, or it's meant to only work on that Spicetify version?
> 
> Thanks.

It's an old edit. Everything's working for me on spicetify 2.8.3

**Comment by UmerF** [comment]
> 

Hmm, odd. I guess I could try a fresh install, delete everything and do it from scratch and see how that goes.

**Comment by UmerF** [comment]
> > Long shot, but just confirming. My Spicetify version is upgraded and it's 2.8.2, and your repo mentions 2.7.0 — is that just an old edit, or it's meant to only work on that Spicetify version?
> > Thanks.
> 
> It's an old edit. Everything's working for me on spicetify 2.8.3

Hmm, odd. But if it's working for you, I guess I could try a fresh install, delete everything and do it from scratch.

**Comment by CyberNiinja** [comment]
> Not sure what is causing this issue, can you try increasing the timeout in fluent.js like shown: [williamckha/spicetify-fluent@4e02067](https://github.com/williamckha/spicetify-fluent/commit/4e02067268b1c876f4f3e5df49d0448ded663227) and see if it fixes the issue? Or you can try reinstalling Fluent from my repo https://github.com/williamckha/spicetify-fluent/

Okay, so I tried increasing the timeout before reinstalling fluent from your repo. neither worked. I increased it after reinstalling too, but that didn't fix it either. I'll try to debug it later. Do you want me to close this issue and open it in your repo?

**Comment by williamckha** [comment]
> > Not sure what is causing this issue, can you try increasing the timeout in fluent.js like shown: [williamckha/spicetify-fluent@4e02067](https://github.com/williamckha/spicetify-fluent/commit/4e02067268b1c876f4f3e5df49d0448ded663227) and see if it fixes the issue? Or you can try reinstalling Fluent from my repo https://github.com/williamckha/spicetify-fluent/
> 
> Okay, so I tried increasing the timeout before reinstalling fluent from your repo. neither worked. I increased it after reinstalling too, but that didn't fix it either. I'll try to debug it later. Do you want me to close this issue and open it in your repo?

You can open an issue in my repo, but keep this issue open until it is resolved/commits are made to this repo. Thanks!

**Comment by afonsojramos** [comment]
Fluent is now being developed [here](https://github.com/williamckha/spicetify-fluent/). Thank you!
