### ISSUE TITLE
Dribbblish Album Preview icon broken

### ISSUE THREAD

**Issue by Sonicx9876** [spicetify/spicetify-themes#619]
![Screenshot 2021-11-22 183930](https://user-images.githubusercontent.com/87156430/142963873-42278227-2f1f-478b-a14a-0da0db3d0ba3.png)
The preview icon is broken and not where it is supposed to be.

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version [1.1.72.439.gc253025e]
 - Spicetify version [2.7.0]
 - Dribbblish

**Comment by UmerF** [comment]
Same issue with Fluent, too.

![8G68OwL](https://i.imgur.com/76A1FfF.png)

**Comment by YSOYT** [comment]
Same Problem Here
![image](https://user-images.githubusercontent.com/79786546/158375565-0f385321-d9c8-42d0-be1f-32afed8384f3.png)

**Comment by kyrie25** [comment]
Resolved via #793
