### ISSUE TITLE
[Fluent] Missing/Misaligned Media Controls During Playback of Podcasts

### ISSUE THREAD

**Issue by retroNUC** [spicetify/spicetify-themes#627]
**Describe the bug**
While listening to a podcast:
- Back/Play/Forward media control icons are vertically misaligned
- Several media control buttons are missing (playback speed, 15s back, 15s forward)

**Screenshots**
With theme:
![image](https://user-images.githubusercontent.com/71151161/143868178-15b47209-102c-41b5-8271-ab26f8e3b871.png)
Without theme:
![image](https://user-images.githubusercontent.com/71151161/143869727-06d4cb97-fc32-43dc-a26f-6bebc8813a16.png)

**Logs**
![image](https://user-images.githubusercontent.com/71151161/143868605-58d4994a-88c3-464c-8ae1-5dd40441a930.png)

**Specifics (please complete the following information):**
 - OS: Windows 11 Home (21H2 22000.318)
 - Spotify: 1.1.73.517.gbef50fdb
 - Spicetify: 2.8.3
 - Theme: Fluent

**Comment by retroNUC** [comment]
Looks to be a reopening of this issue - https://github.com/morpheusthewhite/spicetify-themes/issues/571

I have installed latest theme files from Github as of right now, did the .js copy, etc.

**Comment by williamckha** [comment]
Thanks @SpaceCan for the patch. The CSS labels keep changing too often for me to always update them. I'll try implementing a fix using aria-label selector when I have time

**Comment by kyrie25** [comment]
Theme no longer maintained in this repo, closing issue.
