### ISSUE TITLE
[Fluent] The play icon on the Sidebar is misaligned, also search bar.

### ISSUE THREAD

**Issue by rittennig** [spicetify/spicetify-themes#635]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version.
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
The Play icon on the side bar in liked button is misaligned.
The image below shows.
![image](https://user-images.githubusercontent.com/76802645/145232823-ef3aa0cc-fea3-491f-b005-88583a49e7a4.png)
See the Liked button, the play button is misaligned.

ALSO

The Search bar in search section has some glitches and misalignment.
See the image below.
![image](https://user-images.githubusercontent.com/76802645/145233215-c3d86d2f-aa24-4ac8-8fca-983eb4b60253.png)

The search icon is at center and the text is over it or under it.

**To Reproduce**
The first one, play a song from your liked playlist. (Doesn't happen with other playlist. )
The second one go-to search page.

**Expected behavior**
First one, the icon should be centered.
Second one, I'm not sure how it is supposed to look.

**Screenshots**
Screenshots are proved in explanation section but here it is again. 
![image](https://user-images.githubusercontent.com/76802645/145232823-ef3aa0cc-fea3-491f-b005-88583a49e7a4.png)
![image](https://user-images.githubusercontent.com/76802645/145233215-c3d86d2f-aa24-4ac8-8fca-983eb4b60253.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
![image](https://user-images.githubusercontent.com/76802645/145234184-89c98751-8509-458c-89ce-acfaedc64f84.png)
```

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version : 1.1.73.517.gbef50fdb
 - Spicetify version spicetify v2.8.3
 - Theme name: Fluent

**Comment by actualdankcoder** [comment]
I have a very similar issue

The text in the search bar is misaligned
![image](https://user-images.githubusercontent.com/60839576/151650164-ad336503-696a-41e2-948e-52b2df95f318.png)

The playlists text appeared to be out of bounds as well
![image](https://user-images.githubusercontent.com/60839576/151650186-fc6ad331-8421-458b-9267-2ab1b39f70fd.png)

**Comment by afonsojramos** [comment]
Fluent is now being developed [here](https://github.com/williamckha/spicetify-fluent/). Thank you!
