### ISSUE TITLE
[Ziro] Class name in user.css is incorrect

### ISSUE THREAD

**Issue by cdtinen** [spicetify/spicetify-themes#636]
Lines 478, 484, and 487 in the `user.css` file have incorrect class names. The correct class name is `.playback-bar__progress-time-elapsed`. Currently, the word `elapsed` is missing. Also, the value in line 485 is off, I changed it to 40px.

**Comment by morpheusthewhite** [comment]
Can you open a PR for that?

**Comment by morpheusthewhite** [comment]
@schnensch0

**Comment by cdtinen** [comment]
> Can you open a PR for that?

[PR#638](https://github.com/morpheusthewhite/spicetify-themes/pull/638)
