### ISSUE TITLE
"most popular" is not painted

### ISSUE THREAD

**Issue by Senliast** [spicetify/spicetify-themes#637]
**Prerequisites**
Done

**Describe the bug**
After updating to the most recent Spotify and Spicetify versions, every light theme i install, doesnt paint "most popular", it remains white. I tried with multiple light themes, all the same.

**To Reproduce**
1. Install for example, Ziro theme, with "orange-white" color scheme.
2. Go to "Library"

**Expected behavior**
The "most popular" will be painted and will be black or some appropriate color for light background.

**Screenshots**
https://imgur.com/a/GYymhW8

**Logs**
```console
vendor~xpui.js:29 MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 change listeners added. Use emitter.setMaxListeners() to increase limit
    at c (https://xpui.app.spotify.com/vendor~xpui.js:29:2669302)
    at t.o.addListener (https://xpui.app.spotify.com/vendor~xpui.js:29:2671886)
    at https://xpui.app.spotify.com/vendor~xpui.js:29:2302835
    at Pa (https://xpui.app.spotify.com/vendor~xpui.js:29:2907104)
    at Is (https://xpui.app.spotify.com/vendor~xpui.js:29:2930836)
    at t.unstable_runWithPriority (https://xpui.app.spotify.com/vendor~xpui.js:29:3144419)
    at gr (https://xpui.app.spotify.com/vendor~xpui.js:29:2876640)
    at ks (https://xpui.app.spotify.com/vendor~xpui.js:29:2930615)
    at Os (https://xpui.app.spotify.com/vendor~xpui.js:29:2915494)
    at vs (https://xpui.app.spotify.com/vendor~xpui.js:29:2914416)
c @ vendor~xpui.js:29
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/696.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/367.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
```

**Specifics (please complete the following information):**
 - OS: Windows 10 Pro x64 21H1 19043.1266
 - Spotify version: 1.1.73.517.gbef50fdb
 - Spicetify version: 2.8.3
 - Theme name: Ziro orange-light, Fluent light

**Comment by ohitstom** [comment]
![image](https://user-images.githubusercontent.com/22730962/145472096-c9168db6-c43c-497f-9773-54f6f04f7c51.png)
Heres the css in question for those who will fix it, seems like its not inheriting from the "--" flag set in user.css, could be due to one being hex and the other rgb but i doubt it. This is on ziro aswell i havent tried other light mode themes.
