### ISSUE TITLE
Sleek Timer 

### ISSUE THREAD

**Issue by OliDMX** [spicetify/spicetify-themes#642]
**Describe the bug**
When i use the Sleek Theme the Timer Bar is not at the Position like how it is in the Screenshots, there is a little gap between the pause etc. and at the right corner is the Timer e.g. 1:56 / 3:10. 

**To Reproduce**
Idk, i just launched the Theme and it were there.

**Expected behavior**

**Screenshots**
https://prnt.sc/22sric0

```console
https://prnt.sc/22srvax
```

Specs:
 - OS: Windows 10
 - Spotify version 1.1.74.631.g0b24d9ad
 - Spicetify version v.2.8.3
 - Theme name Sleek

**Comment by morpheusthewhite** [comment]
That's the Sleek theme, why do you mention Dribbblish in the issue?

**Comment by OliDMX** [comment]
Sorry im kinda confused which one it is i downloaded the dribblish too and yeah im confused then i mean sleek sorry

**Comment by morpheusthewhite** [comment]
@harbassan

**Comment by fosam** [comment]
Can't see any screenshots, can you post here?

**Comment by OliDMX** [comment]
![download-1](https://user-images.githubusercontent.com/96055910/146834181-ec5e0e81-5322-4f2b-a6e4-027f00f1bd2c.png)

**Comment by fosam** [comment]
Can't reproduce this scenario, restore spotify to original state and try to apply the latest sleek theme.
