### ISSUE TITLE
Dribbblish

### ISSUE THREAD

**Issue by Bombervan11** [spicetify/spicetify-themes#676]
**Describe the bug**
play/pause button have same color green on green background

**Screenshots**
![image](https://user-images.githubusercontent.com/56171317/152544257-87c5db53-36e7-441c-8768-22235253409b.png)
**Logs**
![image](https://user-images.githubusercontent.com/56171317/152544223-40132c6e-c6bd-4c27-9c93-044f70b9ef5f.png)

```console
(Please paste here console logs or attach a screenshot)
```

**Specifics (please complete the following information):**
 - OS: Windows 11 pro 21H2
 - Spotify version [1.1.77.643.g3c4c6fc6]
 - Spicetify version [spicetify v2.8.5]
 - Theme name Dribbblish base

**Comment by yslDevelop** [comment]
Mind if I work on this?

**Comment by afonsojramos** [comment]
This is an issue with your CSS mapping. This is not happening on the latest versions.
<img width="244" alt="image" src="https://user-images.githubusercontent.com/19473034/163451926-9cf74a81-0482-4d8c-ac2a-9326abd2061b.png">
