### ISSUE TITLE
Buttons turn green when hovered over

### ISSUE THREAD

**Issue by cheeeeeeez** [spicetify/spicetify-themes#677]
![image](https://user-images.githubusercontent.com/93512930/152636189-04a0921d-4529-40ad-97f6-46f529202b35.png)
Here is an image of me placing my cursor over the playlist card.

![image](https://user-images.githubusercontent.com/93512930/152636206-92b44e3e-6f9f-47ae-be11-fcf6fb6b8092.png)
Here is an image where I hover over the play button.

This happens across all themes, I think the option to change it isn't in the colour files as I've gone through each possible value and nothing seems to change it. If I missed a solution somewhere, feel free to close the issue and let me know, I'm not terribly familiar with Spicetify themes.

**Comment by morpheusthewhite** [comment]
That's probably because you missed an update of Spicetify. Please upgrade to the latest version.

**Comment by BudgetLS** [comment]
Have you figured out what the Problem was? I am still having it even tho i am on the newest Versions.

**Comment by ActuallyLemons** [comment]
I am having the same issue even though I'm on the newest version, same issue present in previous versions. Only fix we got here was go to the newest version and then it got closed. Does someone know the actual fix?
