### ISSUE TITLE
[Black] Please update Black theme

### ISSUE THREAD

**Issue by DarkReaper231** [spicetify/spicetify-themes#690]
I used it a lot in my full black rice and I recently updated spotify which meant I had to update spicetify and man no other theme really fits my needs. I mean I tried changing colors but it just ain't it.

**Comment by harbassan** [comment]
Isn't the black theme just the default spotify with different colors?

**Comment by yslDevelop** [comment]
Hi, I would like to take this issue if it's ok.
me and my team could think of 'dark enough' theme that fits DarkReaper's taste.

**Comment by DarkReaper231** [comment]
Well I wish there was pitch black theme. Like #000000

**Comment by harbassan** [comment]
Have you tried the ultrablack scheme of Sleek?

**Comment by yslDevelop** [comment]
Me and my team made the theme that is made of black and gray. We will update the required files shortly 😀

**Comment by afonsojramos** [comment]
I guess this issue can now be closed, thanks!
