### ISSUE TITLE
Blank screen on arch

### ISSUE THREAD

**Issue by Celibistrial** [spicetify/spicetify-themes#706]
When i run 
```
sudo -E spicetify apply
```
Spotify loads up with a black screen 
using this version of [spotify](https://aur.archlinux.org/packages/spotify-snapstore)

**Comment by afonsojramos** [comment]
First of all, do not install spicetify as sudo 😅 But this seems like a topic to ask for help in Discord. please ask there for help

**Comment by Celibistrial** [comment]
Alright thanks , also without sudo it gives errors saying permission was denied

**Comment by Celibistrial** [comment]
![image](https://user-images.githubusercontent.com/82810795/161091134-653e3245-ab44-4722-84a2-cfb7c27757b2.png)
![image](https://user-images.githubusercontent.com/82810795/161091156-444030f9-4e9e-482d-b4c6-e664d8b5973c.png)
I asked around in the discord server other people are also having the same issue, maybe worth looking into?

**Comment by afonsojramos** [comment]
Just noticed that this is `spicetify-themes`. Please check if this issue already exists on `spicetify-cli`, if not please replicate it there! Thanks!
