### ISSUE TITLE
[Ziro] "CONNECT WITH FACEBOOK" text disappear

### ISSUE THREAD

**Issue by ian-Liaozy** [spicetify/spicetify-themes#712]
**Describe the bug**
When trying to add new friends on Spotify, the text on the button disappears.

**To Reproduce**
1. Go to 'Friend Activity'
2. Click on the add button
3. See the error on the sub-page

**Expected behavior**
The text information on the button.

**Screenshots**
https://raw.githubusercontent.com/ian-Liaozy/spicetify-themes/master/images/spicetify-1issue.png

**Specifics:**
 - Spotify version [1.1.81.604.gccacfc8c]
 - Spicetify version [2.9.2]
 - Theme name: Ziro

**Comment by Ruixi-Zhang** [comment]
We found the solution to this issue. It is because the text color is the same as the button. For example, if we change the text color to white, the text can be distinguishable. Should we submit a pull request? Or should we wait for @schnensch0 to fix it?

**Comment by afonsojramos** [comment]
Please do open a PR if you can @Ruixi-Zhang!
