### ISSUE TITLE
[Vaporwave] Theme got lost during migration 

### ISSUE THREAD

**Issue by LivingWithHippos** [spicetify/spicetify-themes#717]
The theme was lost during the migration because I wasn't pinged ;D I stopped using spotify for a while on my pc so I did not notice it. This is just a reminder for myself so I can update it and open a PR when it's ready

**Comment by afonsojramos** [comment]
Heyy! Awesome, please open the PR when possible!

**Comment by harbassan** [comment]
If you're not planning to significantly change the CSS from the default, but rather just to create some cool new color schemes, you should probably just add them as color schemes to the default theme. Just for the sake of clarity and all that. 👍
