### ISSUE TITLE
All Themes: Maintainer Needed ⚠️ 🆘  

### ISSUE THREAD

**Issue by afonsojramos** [spicetify/spicetify-themes#720]
Hello guys! 

If you've been following the development of **Spicetify** and its themes you know that its original maintainer is no longer actively participating in the development/maintenance of Spicetify (but he's still around, looking 👀).

As such, t**his theme is needing someone to actively maintain it**. So, please feel free to volunteer yourselves below! And let's keep this theme alive!! 

Thank you all for the support and active contributions <3

**Comment by Harsh3363** [comment]
Hey i would be intrested in helping you in this

**Comment by harbassan** [comment]
Still needed...
