### ISSUE TITLE
[Theme-name] 

### ISSUE THREAD

**Issue by LegendSlayer265** [spicetify/spicetify-themes#736]
Bug: Spicetify themes bug, when it updated i just ran the commands as normal: `spicetify upgrade` and then `spicetify restore backup apply` and then it opens the spotify app but it simply does not pop any prompt or load the default theme, just kept stuck with the background of the actual theme, firstly i tried restoring spicetify, thhing that unapplies the themes and extensions, that worked cause lit was the raw spotify app, then when i tried applying the themes and extensions i had before, it just didn't worked, just happens the same thing, stucked in the theme bg; i reinstalled both spotify and spicetify, but it just not worked, kinda think the marketplace and the auto install of it brokes spicetify cause it dont logs anything on the config file and with the updates just don't apply those.

1. Update spotify and spicetify
2. run `spicetify upgrade` |  `spicetify restore backup apply`
3. wait for the update
4. See error Theme ... not found | extension ... not found
5. Spicetify opens but kept stucked in the bg

**Expected behavior**
I expected to open spotify app with the theme and extensions i had installed before the update

**Screenshots**
![image](https://user-images.githubusercontent.com/61634000/164571506-6ff55141-7297-43cc-a385-af3c733b7e65.png)
![image](https://user-images.githubusercontent.com/61634000/164571580-172d9863-922b-4416-8704-500c31b50dc8.png)

Logs: don't let me open the console log with ctrl+shift+I

 - OS: Windows 11
 [Backup]
 version = 1.1.83.956.gbe7ea9a7
 with    = 2.9.5
 - (tried with Dribbblish base and Bloom Dark)

**Comment by afonsojramos** [comment]
This is unrelated to this repo and is already being tracked in https://github.com/spicetify/spicetify-cli/issues/1599.
