### ISSUE TITLE
[Dribblish] Color theme changes not working

### ISSUE THREAD

**Issue by AA2B** [spicetify/spicetify-themes#738]
Hello. I've redownloaded spicetify after quite some time and I wanted to try out the Dribblish theme. The installation worked fine, and I added the theme from the marketplace. When trying to change the color theme using powershell, after the restart, the Spotify window would flash the color that I picked, go back to the default green and change nothing. I've tried this with a number of themes and nothing seems to be working. Anything I might be doing wrong?

**Comment by Didibarros** [comment]
Probably not. I have the same issue and thought it was common. Have been looking for a solution for the last few hours and I got nothing. My last hope is this thread.

**Comment by Didibarros** [comment]
By the way, mine also has a little design flaw. Whatever I'm listening to with Dribbblish on, I have an awkward "black box" (if I can call it that) around the name and the artist of the song. Does it happend with you aswell?

**Comment by Cachiey** [comment]
This has also happened to me and Ive tried re installing spicetify and nothing has changed

**Comment by adilsheeth** [comment]
Hi! So I know it's been a while since you brought up this issue, but, for anyone else who's desperately searching for an answer, all I had to do was delete any themes that were in the Marketplace section, as it was interfering with the config file, for some reason. Hopefully this helps :)

**Comment by terminalPoltergeist** [comment]
> Hi! So I know it's been a while since you brought up this issue, but, for anyone else who's desperately searching for an answer, all I had to do was delete any themes that were in the Marketplace section, as it was interfering with the config file, for some reason. Hopefully this helps :)

It's often the simplest changes that have the biggest impacts.. this too worked for me.. thank you.
