### ISSUE TITLE
Theme color scheme issue

### ISSUE THREAD

**Issue by Rechra** [spicetify/spicetify-themes#744]
hello i just reinstalled spicetify due to it's missing by itself. but then i just realised that the theme color scheme is bugged after reinstalling, they didn't shown as list as shown below
![image](https://user-images.githubusercontent.com/104326899/164997728-09df81c8-d97d-48a3-a917-a6a555bb9f10.png)
then i tried to change it from powershell with this command
![image](https://user-images.githubusercontent.com/104326899/164997737-d961a1c5-8c90-4349-9891-d9684381e00d.png)
it restart the spicetify, but when it launched again the theme is still remain the same with wealthy
is there any other way to change the scheme color?

**Comment by afonsojramos** [comment]
I believe this has to do with you installing through Marketplace, but I am not sure... 🤔 @spicetify/marketplace

**Comment by CharlieS1103** [comment]
@afonsojramos Yup.
