### ISSUE TITLE
[Default] Play button dissapear

### ISSUE THREAD

**Issue by nanchaara** [spicetify/spicetify-themes#748]
**Describe the bug**
Play button dissapear, but still can be clicked

**To Reproduce**
just look on the navbar

**Expected behavior**
Play button to reappear.

**Screenshots**
![image](https://user-images.githubusercontent.com/71387731/166096952-2e31a3dd-7888-4ed8-8550-62f55cc46a2c.png)

**Logs**
I cant open console log even if i have enabled it.

**Specifics (please complete the following information):**
 - OS: Windows 11 Pro - 21H2 - 22000.652
 - Spotify version : 1.1.84.716.gc5f8b819
 - Spicetify version 2.9.8
 - Default

**Comment by Blacksuan19** [comment]
If you want material ocean, try the theme from the GitHub organization [here](https://github.com/material-ocean/Spotify-Theme), The one used here as default is incomplete and old.

**Comment by nanchaara** [comment]
> If you want material ocean, try the theme from the GitHub organization [here](https://github.com/material-ocean/Spotify-Theme), The one used here as default is incomplete and old.

![image](https://user-images.githubusercontent.com/71387731/166099363-f0ff49a0-2306-4aa6-9d7b-1096511e4773.png)
its still dissapear

**Comment by Blacksuan19** [comment]
can you provide more information on when it happens exactly? I don't have the same issue here with latest spotify, spicetify and theme from the link.

![Peek 2022-04-30 22-33](https://user-images.githubusercontent.com/10248473/166109834-43e9d4ae-41df-48e4-8093-89f1e4e047f1.gif)

**Comment by nanchaara** [comment]
it's just happen everytime, no specific condition needed
should i full reinstall spotify?

**Comment by Blacksuan19** [comment]
Do a full clean install and use the theme from repo

**Comment by nanchaara** [comment]
fixed, thanks!
![image](https://user-images.githubusercontent.com/71387731/166146543-322a6028-7d4e-461f-aed2-3a7537627852.png)
