### ISSUE TITLE
Scrollbars outside Spotify (I Think)

### ISSUE THREAD

**Issue by ShivaPrakash-006** [spicetify/spicetify-themes#751]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.84.716.gc5f8b819
- Spicetify version: v2.9.8
```

### 📝 Description

I opened Spotify and was greeted to this.

There are sidebars outside of the page of Spotify (I Think).

It also shows 'err' when applying it

Check the screenshots to understand what I am saying.

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/87466383/166156244-8ed2d5f3-ffcb-4a82-acdb-ce7223a23a60.png)
![image](https://user-images.githubusercontent.com/87466383/166156275-fb773efb-4f64-49bc-a4a3-7fe1a9d76a83.png)
![image](https://user-images.githubusercontent.com/87466383/166156357-f81d05bf-6319-48d9-8121-a8fbcee85bbf.png)

**Comment by ShivaPrakash-006** [comment]
Anyone?

**Comment by afonsojramos** [comment]
I would suggest a clean install, not sure what is happening here.

**Comment by CharlieS1103** [comment]
Glaze should be solved now.
