### ISSUE TITLE
spotify ui is black

### ISSUE THREAD

**Issue by jasonzgames** [spicetify/spicetify-themes#761]
Theres really nothing else to say its just unusable
![spotify probloms](https://user-images.githubusercontent.com/63572031/169178534-0570b8fa-3e38-4526-8b81-24b2f43671ba.PNG)

**Comment by XordK** [comment]
closed as completed? At least tell how to fix.

**Comment by afonsojramos** [comment]
Tracking of this issue is under #1660.
