### ISSUE TITLE
Themes do not change

### ISSUE THREAD

**Issue by syunohito** [spicetify/spicetify-themes#762]
![image](https://user-images.githubusercontent.com/72976164/169251119-ee55faf1-1398-4cea-87e9-0118339a8428.png)
spotify updated automatically and spicetify is no longer available, so I lowered the spotify version by one and now I can't change the theme!

**Comment by afonsojramos** [comment]
Did you install the other one through Marketplace?

**Comment by syunohito** [comment]
![image](https://user-images.githubusercontent.com/72976164/169307683-834e5b5c-ba10-49d7-89a6-4e448e659745.png)
I removed the theme from the marketplace and the theme is now PINK. Thank you!

**Comment by syunohito** [comment]
love spivetify
