### ISSUE TITLE
UI Bug opening Lyrics

### ISSUE THREAD

**Issue by Elacto** [spicetify/spicetify-themes#765]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.85.895.g2a71e1b8
- Spicetify version: 2.9.9
```

### 📝 Description

When using Spicetify on my second monitor (half of it pic.1). Then I pressed the microphone to look at the lyrics and the whole overlay (pic.2). When switching back to normal the Overlay didn't move back (pic.3). Only after Restarting Spotify the Overlay went back to normal (pic.4).

### 📸 Screenshots

![2](https://user-images.githubusercontent.com/106095394/169853842-9cae1c52-d4cc-4d36-802b-14eaf0989910.PNG)
![1](https://user-images.githubusercontent.com/106095394/169853853-f1699e6e-487c-4a8a-a6bc-11f3e7b94e2f.PNG)
![4](https://user-images.githubusercontent.com/106095394/169853865-41c7787f-efb3-4fb9-b226-e87dc6e681d4.PNG)
![3](https://user-images.githubusercontent.com/106095394/169853873-a994706e-6821-42aa-ba5c-9bebe06664fe.PNG)

**Comment by afonsojramos** [comment]
What overlay are you talking about?

**Comment by Elacto** [comment]
@afonsojramos Like shown in the pictures, im talking about the UI that shows your playlists and library. It shifts to the left and stays there.
