### ISSUE TITLE
playlist icons not loading

### ISSUE THREAD

**Issue by danielmontgomer** [spicetify/spicetify-themes#769]
the playlist icons will not appear or load on my dribblish it is up to date 
![image](https://user-images.githubusercontent.com/105879134/170094260-f1daf950-c3b1-4a2d-9fd0-5cc2c271dfc8.png)

**Comment by afonsojramos** [comment]
Do you have the required Patch section in your config?

```ini
[Patch]
xpui.js_find_8008 = ,(\w+=)32,
xpui.js_repl_8008 = ,${1}56,
```

**Comment by danielmontgomer** [comment]
yes, still not working

**Comment by afonsojramos** [comment]
Try again with the new version!

**Comment by Twitchpukki** [comment]
![Sieppaa](https://user-images.githubusercontent.com/72289402/174467996-0f3c5c84-ad8b-417d-8eb2-cc559ae7d72d.PNG)
where are the sidebar icons?

**Comment by lmcr666** [comment]
> Do you have the required Patch section in your config?
> 
> ```ini
> [Patch]
> xpui.js_find_8008 = ,(\w+=)32,
> xpui.js_repl_8008 = ,${1}56,
> ```

what is the config file? i've looked everywhere, is it where spotify is installed? is it a file in spicetify? what is the "config file"?

**Comment by kyrie25** [comment]
Resolved in latest patch of Dribbblish.
