### ISSUE TITLE
[Sleek] End time showing without Hover

### ISSUE THREAD

**Issue by Tetrax-10** [spicetify/spicetify-themes#772]
End time used to display when we hover on the progress bar, now it's showing without hover. it happened after updating my Spotify and spicetify.

![issue](https://user-images.githubusercontent.com/75513645/170828767-0d69ec84-97e8-487f-b984-31108d65123c.png)

 - OS: [Windows 11]
 - Spotify version [1.1.85.895.g2a71e1b8]
 - Spicetify version [2.10.1]
 - Sleek

**Comment by kyrie25** [comment]
Resolved via spicetify/spicetify-cli#1819
