### ISSUE TITLE
[Dribbblish] Theme is completely broken

### ISSUE THREAD

**Issue by ps13g** [spicetify/spicetify-themes#774]
**Describe the bug**
The Dribbblish theme is completely broken after updating to 2.10.1
**To Reproduce**
1. Upgrade to 2.10.1 
2. Open Spotify

**Screenshots**

<img width="1512" alt="Screen Shot 2022-05-28 at 6 51 27 PM" src="https://user-images.githubusercontent.com/84423124/170847503-6c7f5bb0-8cb6-486f-8f93-1040b4898fe2.png">

**Specifics (please complete the following information):**
 - OS: macOS 12.4
 - Spotify version: 1.1.86.857.g3751ee08
 - Spicetify version: 2.10.1

**Comment by afonsojramos** [comment]
Please refer to #720 for help!

**Comment by Nycz-lab** [comment]
i am also using spicetify v 2.10.1 however for me the theme is working flawlessly

**Comment by kyrie25** [comment]
You're using Dribbblish Dynamic which is not maintained in this repository. Closing issue.
