### ISSUE TITLE
[Flow] The Spotify controls are not being displayed properly 

### ISSUE THREAD

**Issue by Mazbrew** [spicetify/spicetify-themes#779]
**Describe the bug**
Spotify controls bar is not being displayed properly.
Control are not there and cannot be interacted

**To Reproduce**
Open the app.

**Expected behavior**
Controls should be displayed vertically.

**Screenshots**
<img width="1393" alt="Screenshot 2022-06-04 at 11 06 13 AM" src="https://user-images.githubusercontent.com/82868826/171977646-0504fa6a-fcd7-458c-85d1-56bde5c4d345.png">

**Specifics (please complete the following information):**
 - OS: macOS 12.4
 - Spotify version 1.1.86.857.g3751ee08
 - Spicetify version 2.10.1
 - Flow

**Comment by smoke-of-alder** [comment]
Same issue.
OS Edition: Windows 10 Pro
OS Version: 21H1
Spotify version: 1.1.87.612.gf8d110e2
Spicetify version: master (2.10.1)
Flow

**Comment by Pleasant-exe** [comment]
All themes seem to be broken

**Comment by kyrie25** [comment]
Can't replicate on Spotify 1.1.89 & Spicetify 2.10.2
![Spotify_NXuw7vy2Ky](https://user-images.githubusercontent.com/77577746/178987560-59a53592-4c87-4a9a-b3ea-97db343116fe.gif)
Upgrade Spicetify, run `spicetify restore backup apply` and try again.

**Comment by kyrie25** [comment]
Resolved CSS map issue.

**Comment by caioolivv** [comment]
> Can't replicate on Spotify 1.1.89 & Spicetify 2.10.2 ![Spotify_NXuw7vy2Ky](https://user-images.githubusercontent.com/77577746/178987560-59a53592-4c87-4a9a-b3ea-97db343116fe.gif)  Upgrade Spicetify, run `spicetify restore backup apply` and try again.

Should the volume control look like this? Mine still looks weird

![Screenshot from 2022-11-10 00-14-54](https://user-images.githubusercontent.com/38115797/200992423-b4f8cccb-f212-4e2c-a4d3-7c8248e28cee.png)
