### ISSUE TITLE
[Glaze]  Track information is not appearing

### ISSUE THREAD

**Issue by CharlieS1103** [spicetify/spicetify-themes#780]
**Describe the bug**
Track information is not showing on Glaze theme

**Screenshots**
<img width="1440" alt="Screen Shot 2022-06-04 at 12 34 26 PM" src="https://user-images.githubusercontent.com/60494758/172016598-436c7070-3edf-4d52-b6e0-40bcf4068f11.png">

**Comment by kyrie25** [comment]
Spotify fixed it on latest update.
![image](https://user-images.githubusercontent.com/77577746/183559553-4f0acdc2-4bab-4ea3-9b8e-ba41b67d9780.png)
