### ISSUE TITLE
[Dribbblish] Colorscheme request: Rose Pine

### ISSUE THREAD

**Issue by the-argus** [spicetify/spicetify-themes#783]
I made a rose-pine dribblish color scheme, its just a simple entry to the INI file. Preview [here](https://i.redd.it/260nn8qn29591.png), in the bottom most screenshot: 

I'll make a PR if this is a welcome addition.

**Comment by kyrie25** [comment]
Of course! PRs are always welcomed, feel free to make one and we'll look into it ASAP. Remember to add in up-to-date screenshots in the PR description :)

**Comment by afonsojramos** [comment]
@the-argus ping as a reminder 👀
