### ISSUE TITLE
[Dribbblish] Works but has bugs

### ISSUE THREAD

**Issue by M1ndo** [spicetify/spicetify-themes#788]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version. (YES)
2. Your Spotify version is compatible with the `spicetify` version you are using. (YES LATEST SUPPORTED)
3. You have the most recent version of the themes. (YES)
4. You followed the installation instructions for the theme you are using (please go through the entire theme README). (YES)

**Describe the bug**
The Theme works but has some bugs that need to be patched.
1. No icons in playlists tab
2. Lyrics window is not like it used to be.

**To Reproduce**
1. Make sure you have latest spotify and spicetify and installed the theme

**Expected behavior**
Clear of bugs like it used to be.

**Screenshots**
![image](https://user-images.githubusercontent.com/44820142/175647736-28c04509-d817-49f2-8442-bcdc5d78d136.png)
![image](https://user-images.githubusercontent.com/44820142/175647788-896fc3df-9b4f-4b11-929b-4346e0a5d82b.png)

**Specifics (please complete the following information):**
 - OS: DarkOs (Arch)
 - Spotify version [e.g. 1.1.84.716.gc5f8b819]
 - Spicetify version [e.g. 2.10.1]
 - Theme name (Dribbblish)

**Comment by kyrie25** [comment]
You're using the incorrect version of Spicetify, downgrade to 2.9.9 as it is compatible with 1.1.84.
Both issues can't be reproduced in the latest version of the theme, update theme and see if it still occurs.
