### ISSUE TITLE
[Dribbblish]  The covert art is broken

### ISSUE THREAD

**Issue by Pranav18062004** [spicetify/spicetify-themes#789]
The cover art of the music is shown wierdly and the whole music control has shifted upwards

![Screenshot 2022-06-26 184616](https://user-images.githubusercontent.com/79793482/175815944-02de7b18-2f32-4a0c-b43b-f0a04d1fe620.png)

**Comment by kyrie25** [comment]
Seems like it works perfectly fine in the current version, do you still have the same issue?

**Comment by kyrie25** [comment]
Resolved CSS map issue.
