### ISSUE TITLE
[Sleek] Create Playlist constantly highlighted

### ISSUE THREAD

**Issue by Nerxxy** [spicetify/spicetify-themes#791]
### 🔍 Have you checked Spicetify.app page for your issue?

- [X] I have checked the FAQ

### 🔍 Is there already an issue for your problem?

- [X] I have checked older issues, open and closed

### ℹ Environment / Computer Info

```Markdown
- Spotify version: 1.1.88.612.gcc529952
- Spicetify version: 2.10.2
```

### 📝 Description

Create Playlist is acting as if its constantly being hovered over.

To reproduce: Be on the same spotify and spicetify version, (possibly/not sure if it will affect it) use Sleek theme

### 📸 Screenshots

![image](https://user-images.githubusercontent.com/37718547/176031608-b568db0b-e050-4883-b139-3ea67bc1a08f.png)

**Comment by Nerxxy** [comment]
Just checked, is indeed a Sleek theme issue

**Comment by kyrie25** [comment]
Can't replicate on Spotify 1.1.89 & Spicetify 2.10.2
![image](https://user-images.githubusercontent.com/77577746/178988575-26607817-e758-4581-b111-bf73f8146f6c.png)
Do you still have the same issue?

**Comment by Nerxxy** [comment]
> Can't replicate on Spotify 1.1.89 & Spicetify 2.10.2 ... Do you still have the same issue?

ive not updated spiectify yet as have been busy the last week will give it a go now

**Comment by kyrie25** [comment]
It is due to new Spotify changes that split these two onto their own classes, but I don't think it's considered broken tbh.
![image](https://user-images.githubusercontent.com/77577746/178997500-33ce4feb-34d4-47a0-bb6a-23c1bd8c1264.png)
