### ISSUE TITLE
[Ziro] The numbers below the progress bar are misaligned 

### ISSUE THREAD

**Issue by DeathGhost813** [spicetify/spicetify-themes#792]
**Describe the bug**
The numbers below the progress bar are misaligne
![image](https://user-images.githubusercontent.com/83057121/176359487-32863fa9-e779-43af-bf56-ba8bca85bbf1.png)
 

**Screenshots**
![image](https://user-images.githubusercontent.com/83057121/176359550-010cd5b6-6503-4844-b1de-1c6855c48c70.png)
![image](https://user-images.githubusercontent.com/83057121/176361884-043a31d3-44aa-4a5d-9379-13f1809b5717.png)
![image](https://user-images.githubusercontent.com/83057121/176362454-f173159b-1e65-451a-a9fe-3c94ca58382c.png)

```console
(Please paste here console logs or attach a screenshot)
```

**Specifics (please complete the following information):**
 - OS: Windows11 22000.739
 - Spotify:1.1.88.612.gcc529952
 - Theme name：ziro/purple-dark
 - The latest version of Spicetify

**Comment by cpuccino** [comment]
Damn, ziro's a bit broken, you can add this in for now - just paste it in the user.css for ziro
disclaimer: I've never done spotify theming before, this is a 2 minute hack i wrote cause it was annoying me to death lol (although there's a lot more issues than just the alignment)

```
.playback-bar > *:nth-child(3) {
  position: absolute;
  margin-bottom: 30px;
  right: 265px;
}
```

**Comment by kyrie25** [comment]
> just paste it in the user.css for ziro

Or use the Snippets function on Marketplace of where you installed it from
