### ISSUE TITLE
[Ziro] Time indicators overlap each other

### ISSUE THREAD

**Issue by g0ld3nl34f** [spicetify/spicetify-themes#796]
**Describe the bug**
Time indicators overlap as seen in the provided screenshot.

**To Reproduce**
1. Install spicetify-themes.
2. Set Ziro as current theme.
3. Choose any color variation.
4. Open Spotify client.

**Expected behavior**
Time indicators do not overlap.

**Screenshots**
As shown in the README for the theme:
![expected](https://user-images.githubusercontent.com/34871398/177300805-9f3ebb25-8386-49af-b555-c27eda768f47.png)
What is actually displaying:
![real](https://user-images.githubusercontent.com/34871398/177301025-a5de3831-9cdf-4de8-b3a6-97af32904b90.png)

**Specifics (please complete the following information):**
 - OS: Pop!_Os 21.10
 - Spotify version: 1.1.84.716.gc5f8b819
 - Spicetify version: 2.10.2
 - Theme name: Ziro

**Comment by kyrie25** [comment]
Ziro is currently compatible with 1.1.87 and higher in accordance to the recent patch, so patching 1.1.84 probably won't be our focus. Nonetheless, do feel free to make a PR if you managed to patch it!

**Comment by g0ld3nl34f** [comment]
I fixed it. The time indicators had the same exact values for right padding. I'll make the PR as suggested since the most up-to-date client for Linux seems to be 1.1.84 as far as I know.
