### ISSUE TITLE
[Dreary] Playlist Names not displaying correctly on left sidebar

### ISSUE THREAD

**Issue by JeannasBro** [spicetify/spicetify-themes#797]
The sidebar on the left is not displaying playlist names doesn't fit on the screen correctly, in both Full Screen and windowed

**Screenshots**
Full Screen: https://i.upload.systems/09OEFgCl
Windowed: https://i.upload.systems/ShFnCP7z

As you can see the Playlists on the left are cut off and not displaying correctly

 - OS: Windows 10
 - Spotify version 8.6.96.422
 - Spicetify version 2.10.2
 - Dreary

**Comment by CharlieS1103** [comment]
I am no longer maintaining dreary unfortunately so if it is to be fixed it'll have to be someone else.

**Comment by JeannasBro** [comment]
> I am no longer maintaining dreary unfortunately so if it is to be fixed it'll have to be someone else.

Could you perhaps pass the message to someone who might be able to push a fix? I absolutely love this theme but it's very unsettling that the playlist names look so off. Sorry for any trouble

**Comment by CharlieS1103** [comment]
@JeannasBro I can create an issue on this repo to find a new maintainer

**Comment by JeannasBro** [comment]
> @JeannasBro I can create an issue on this repo to find a new maintainer

That would be awesome thanks!
