### ISSUE TITLE
[Bladerunner - Sleek] 

### ISSUE THREAD

**Issue by jamiejcole** [spicetify/spicetify-themes#799]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version. Yes
2. Your Spotify version is compatible with the `spicetify` version you are using. Yes
3. You have the most recent version of the themes. Yes
4. You followed the installation instructions for the theme you are using (please go through the entire theme README). Yes

**Describe the bug**
Bladerunner colour scheme for Sleek theme has black icons on black background. 

**To Reproduce**
1. Go to any playlist or view the playbar at the bottom of the screen
2. Heart button, next track, previous track, loop, lyrics, volume, fullscreen, devices icons will be black on the black background.

**Expected behavior**
They should be not the same colour as the background, probably the yellow that goes with the theme.

**Screenshots**
![image](https://user-images.githubusercontent.com/48195376/178130762-57b01494-b204-4951-aae2-cf57c721092e.png)
![image](https://user-images.githubusercontent.com/48195376/178130768-3337e5d8-9e19-428e-9670-94c732a86528.png)

**Other**
From inspecting in the console, by changing the color attribute of the various button elements from `rgba(var(--spice-rgb-selected-row),.7);` to `var(--spice-text)`, the colour is fixed. I don't know how to make a PR though so uhhhhhh...

**Specifics (please complete the following information):**
 - OS: Windows 10
 - Spotify version: 1.1.89.862.g94554d24
 - Spicetify version: 2.10.2
 - Theme name: Sleek - Bladerunner

**Comment by kyrie25** [comment]
Can't replicate issue on 1.1.89/2.10.2, run `spicetify restore backup apply` and try again.
![image](https://user-images.githubusercontent.com/77577746/178999395-605ebd41-1aa0-4a37-9954-fe3e25b1e162.png)

**Comment by jamiejcole** [comment]
Running `spicetify restore backup apply` did not work. Although, I reinstalled spicetify marketplace and that seemed to do the trick.
