### ISSUE TITLE
turntable

### ISSUE THREAD

**Issue by Izacdis** [spicetify/spicetify-themes#807]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version.
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
when i try to install and run the code
``` spicetify config current_theme Turntable
spicetify config extensions turntable.js
spicetify apply```
 it gives me a turntable.js not found i have tried to uninstall and reinstall
![image](https://user-images.githubusercontent.com/109758569/180350044-6ea67c40-f033-4657-a56b-db3d172643c9.png)
i am running win 10 4gb ram 64 bit and i always do customization to my laptops and i like this one very much

idk how to get console logs

**Comment by Izacdis** [comment]
![image](https://user-images.githubusercontent.com/109758569/180350762-e49d7fe5-8bed-4aa3-a6ab-b7313c537613.png)

**Comment by kyrie25** [comment]
Not a bug.
Copy the `turntable.js` from the theme folder onto `%appdata%\spicetify\Extensions`

**Comment by Izacdis** [comment]
![image](https://user-images.githubusercontent.com/109758569/180445444-f3803729-edb8-4cdd-a397-1b9cdf3fede6.png)
![image](https://user-images.githubusercontent.com/109758569/180445480-30512d67-7ea6-401f-8b8d-c7c41b6cfae0.png)
![image](https://user-images.githubusercontent.com/109758569/180445511-eb79a836-2411-4b80-a402-44e58f706233.png)
did not fix wont apply
