### ISSUE TITLE
[Ziro] Selecting 'gray' color scheme selects 'blue' scheme instead

### ISSUE THREAD

**Issue by JakubCisowski** [spicetify/spicetify-themes#809]
Both gray and blue color schemes are identical.

 - OS -> Windows 10
 - Spotify version -> 1.1.90.859.gf1bb1e36
 - Spicetify version -> 2.1.1.1
 - Ziro

**Comment by Sasikuttan2163** [comment]
Can you send screenshots? The themes look different to me.

gray-dark
![image](https://user-images.githubusercontent.com/84299080/180591340-cdd3a605-9ae5-4107-9b1a-329c5baa94f0.png)

blue-dark
![image](https://user-images.githubusercontent.com/84299080/180591377-8a491f4a-1bd6-499a-b61c-5666e8c4e907.png)

**Comment by JakubCisowski** [comment]
Ahh, I forgot to add '-dark'.

For some reason all of the three color scheme names:
'gray', 'blue' and 'blue-dark'
select 'blue-dark' scheme for me which got me confused.
