### ISSUE TITLE
[Dribbblish] Significant size of top bar 

### ISSUE THREAD

**Issue by ps13g** [spicetify/spicetify-themes#817]
**Describe the bug**
The top bar for Spotify is too big 

**To Reproduce**
1. Open Spotify

**Screenshots**
<img width="1512" alt="Screen Shot 2022-07-30 at 12 09 04 PM" src="https://user-images.githubusercontent.com/84423124/181936168-facdde7e-8011-49f4-ba0f-8a3227d9d604.png">

**Specifics **
 - OS: macOS 12.5
 - Spotify version: Spotify for macOS (Apple Silicon) 1.1.90.859.gf1bb1e36
 - Spicetify version: 2.11.1

**Comment by kyrie25** [comment]
This is a deliberate feature added on #708 so as to not clip onto 3 dot and window control buttons. If you wish to reduce the size you can manually change the theme or add a custom snippet if you installed it via Marketplace.
