### ISSUE TITLE
[Flow] Theme overlapping and entirely incorrect

### ISSUE THREAD

**Issue by flyday2** [spicetify/spicetify-themes#830]
**Describe the bug**
Flow theme does not fit the full screen and all buttons/screens are overlapping/incorrect

**To Reproduce**
Open Spotify with Flow theme

**Expected behavior**
Expected Spotify to be fullscreen without overlapping (Look like screenshots in read me)

![image](https://user-images.githubusercontent.com/112017221/186501328-7af5ffd3-41d5-46ad-b47e-c6b109458a4e.png)

 - OS: Windows 10
 - Spotify version 1.1.91.824.g07f1e963
 - Spicetify version 2.12.0
 - Flow

**Comment by picarito** [comment]
same here. Any fixes for it yet?

**Comment by tessmmm** [comment]
I had to turn off friend activity and then it worked. I wish I could still see the activity with this theme tho :(
