### ISSUE TITLE
[Dribbblish] Weird bottom bar size on OSX

### ISSUE THREAD

**Issue by Blakeinstein** [spicetify/spicetify-themes#831]
**Expected behavior**
Expected the ui to match the screenshots

**Screenshots**
<img width="426" alt="image" src="https://user-images.githubusercontent.com/42214598/186857820-5094b7be-2e99-4a3a-bf53-a9e942540de4.png">
 
( I do not want to share the entire screen publically, but this is pretty much the crux of the bug)
Most likely a css change.

**Specifics (please complete the following information):**
 - OS: MacOS Monterey v12.5.1
 - Spotify version  1.1.92.647.ga4397eb7
 - Spicetify version 2.12.0
 - Theme name Dribbblish

**Comment by doongs** [comment]
I'm looking into the dev inspector now, but I'm not familiar enough with how this is constructed to fix the issue. Version 1.1.85.895 appears to be the last version without this playbar issue, so comparing the differences between that and the current version looks to be a good starting place.

It's probably a trivial fix, but I don't have a good enough grasp on how the css is laid out to do it myself. I'll dig a little more though.

**Comment by 435vic** [comment]
Should be fixed in the newest version, try reinstalling Dribbblish with the command specified [here](https://github.com/spicetify/spicetify-themes/tree/master/Dribbblish#auto-install)
