### ISSUE TITLE
Dribbblish 

### ISSUE THREAD

**Issue by DaAnubis** [spicetify/spicetify-themes#832]
![Screenshot (156)](https://user-images.githubusercontent.com/112479924/187416758-b73b113e-d512-48a6-bb60-4f1a9c203f4f.png)

**Describe the bug**
So supposedly lyrics should be popping but as u can see nth is popping up I tried installing "Full App Display" Extension but also it's not popping. 

**Specifics (please complete the following information):**
 - OS: Windows 10 
 - Spotify version 1.1.92.647.ga4397eb7
 - Spicetify version 2.12.0
 - Dribbblish

**Comment by kyrie25** [comment]
Not a theme issue nor an extension issue
