### ISSUE TITLE
Can't change default green elements in theme

### ISSUE THREAD

**Issue by ActuallyLemons** [spicetify/spicetify-themes#833]
I made my own custom theme, but in color.ini is no option to change the default spotify green that shows up when you hover over a button, or the "visualiser" that shows up next to the current track.
I'm on the latest version of spicetify and spotify, had the same issue on previous versions.

![Screenshot (63)](https://user-images.githubusercontent.com/112755506/188266002-4a722521-efe4-4e28-8a74-91a049761a55.png)
![Screenshot (62)](https://user-images.githubusercontent.com/112755506/188266019-da67e492-5600-4070-a460-5000661c5fa4.jpg)

**Comment by UrSok** [comment]
The visualiser is an image

**Comment by afonsojramos** [comment]
I was actually able to do it, but I do not

**Comment by afonsojramos** [comment]
I was actually able to do it by using the method suggested in this [StackOverflow post](https://stackoverflow.com/a/53336754).

<img width="220" alt="image" src="https://user-images.githubusercontent.com/19473034/188714812-7403530c-b092-462f-9c15-4736b74d047e.png">

So, by converting the hex color to what the CSS `filter` property requires you can do it, but it is clearly harder than it should.
