### ISSUE TITLE
[Sleek] Cannot change theme color

### ISSUE THREAD

**Issue by notNSANE** [spicetify/spicetify-themes#834]
**Describe the bug**
Cannot change theme color

**To Reproduce**
1. Install Sleek from the Marketplace
2. Use the powershell line to change the theme color, 
3. Apply

**Expected behavior**
Theme changes color preset.

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

![image](https://user-images.githubusercontent.com/7162375/189953006-2d21e5de-e802-4d25-901a-bf55d3124135.png)

**Specifics (please complete the following information):**
 - OS: Windows 11
 - Spotify for Windows 1.1.94.864.g540a4cc6
 - Spicetify version v2.13.1
 - Sleek

**Comment by Shqrp** [comment]
I suggest you use the Marketplace to install the Sleek theme as it's available there.

**Comment by notNSANE** [comment]
I used the marketplace, but I cannot change the color.

**Comment by Shqrp** [comment]
And that's the reason you cannot change your color scheme: to change a marketplace installed theme you must do it from the top right dropdown menu in the marketplace section.
