### ISSUE TITLE
[Dribbblish] UI Issues

### ISSUE THREAD

**Issue by ItsNotOp** [spicetify/spicetify-themes#836]
**Describe the bug**
- The font is default spotify, not Dribbblish themed fonts
- Pause button is missing
- Top green bar is way too big compared to the original
- Bottom green bar has a weird shadow on its edges
- Misaligned & grey buttons on sidebar
- The time length & explicit tags on album is really dark

See image:
![image](https://user-images.githubusercontent.com/69270581/190866458-16ff5def-0ae7-4174-a3b7-07a14465a083.png)

**To Reproduce**
1. Apply Dribbblish theme & latest Spotify/Spicetify versions
2. Open anything in Spotify

**Expected behavior**
![image](https://user-images.githubusercontent.com/69270581/190866445-2382aad4-ea77-4a66-a9be-181c0a2430cb.png)

**Specifics (please complete the following information):**
 - OS: Windows 11
 - Spotify version 1.1.94.870.gf994cb0b
 - Spicetify version v2.13.1
 - Dribbblish

**Comment by Blacksuan19** [comment]
@khanhas issue assignment is kinda broken, any issue with the word default is assigned to me.

**Comment by Potato22** [comment]
even worse for my end
- misaligned icons when the sidebar is fully minimized
- I couldn't scroll further down in the sidebar if you have many playlists
![image](https://user-images.githubusercontent.com/39096741/192085355-17ada64a-4915-4343-88bc-4ec88eed57a0.png)
