### ISSUE TITLE
Hacktoberfest

### ISSUE THREAD

**Issue by Mangeshrex** [spicetify/spicetify-themes#849]
Does this repo accept hacktoberfest contributions. And merge the pr with hacktoberfest-accepted labels ?

**Comment by afonsojramos** [comment]
We can add the label if you request for it, yes.

**Comment by Mangeshrex** [comment]
Awesome! Can you do that please?

**Comment by afonsojramos** [comment]
We'll add the label `hacktoberfest-accepted` on a per request basis for the PRs @Mangeshrex.
