### ISSUE TITLE
[Dribblish] Play Button On Playlists not showing up

### ISSUE THREAD

**Issue by Gam3rrXD** [spicetify/spicetify-themes#852]
Updated everything to the latest version.
<img width="97" alt="image" src="https://user-images.githubusercontent.com/84348006/195950958-9a085124-72b5-4424-b434-279a954c6f39.png">

**Comment by RealPCBUILD3R** [comment]
I have the same issue. How can i fix this?

**Comment by Sasikuttan2163** [comment]
Seems like this issue is occurring only on color schemes which have the same color for `sidebar` and `button-active`
