### ISSUE TITLE
[Onepunch Dark] Weird shadow things in the title of the song.

### ISSUE THREAD

**Issue by poyo20** [spicetify/spicetify-themes#859]
**Describe the bug**
When i play a song, the title shows weird shadows things on the side.

**To Reproduce**
1. Play any song
2. See error

**Screenshots**
See the picture shown here.
[https://imgur.com/a/Ko0zmxq](url)

**Specifics:**
 - OS: openSUSE Tumbleweed
 - Spotify version: Latest
 - Spicetify version: Latest
 - Theme name: Onepunch (Dark variant)

**Comment by RouterDude404** [comment]
Cant see screenshot

**Comment by tamagonocammy** [comment]
![Here's what it looks like.](https://user-images.githubusercontent.com/10888565/203222954-f1b5ed53-7c74-4959-bd42-58008f49cd76.png)
