### ISSUE TITLE
[Sleek] Not updating/changing the UI in latest update

### ISSUE THREAD

**Issue by Oh2Yeah** [spicetify/spicetify-themes#872]
After updating spotify today, after reapplying the sleek theme with psycho colour scheme, the ui doesn't have the marketplace and made for you tabs in the left sidebar. Also, the home and search tab seems to have moved to the top which is not much of an issue but I like to have the marketplace and made for you tabs available in the left sidebar along with your library.

![Spotify_6zm5s36eGa](https://user-images.githubusercontent.com/67186085/205673968-c6220485-60d3-4957-88bf-b2b52033a578.png)
^This is the earlier ui I had [Sleek Psycho]

![Spotify_xngCRTc6tF](https://user-images.githubusercontent.com/67186085/205674120-8c55a2ec-3963-4349-b647-f6bb3720bbde.png)
^This is what I see today just your library up there. [Sleek UltraBlack]

So, did I do something wrong or this can fixed?

**Comment by harbassan** [comment]
Go into experimental features and disable new home UI, should return to normal. You can get to experimental features by the profile menu.
