### ISSUE TITLE
[Sleek] The Blue Tick indicating Verified Artists, is surrounded by a border.

### ISSUE THREAD

**Issue by TheChilledBuffalo** [spicetify/spicetify-themes#875]
**Describe the bug**

The Verified Artist indicator, the blue tick, is surrounded by a border of the same colour as the selected colour scheme in the artists' profile.

**Expected behavior**

The border should not be present.

**Screenshots**

![Screenshot_20221213_051937](https://user-images.githubusercontent.com/87632612/207315457-3944a4ff-5f80-4fb9-b4d2-7de00a1e4825.png)

**Specifics (please complete the following information):**
 - OS: Windows 11 22H2
 - Spotify version: 1.2.0.1165.gabf054ab
 - Spicetify version: 2.14.3
 - Theme name: Sleek (Applicable for all colour schemes)

**Comment by harbassan** [comment]
If you've downloaded the theme through marketplace, it should update in a few hours. If you've downloaded it manually you can just grab the user.css from the repo. Once you see the change close the issue, thanks.

**Comment by TheChilledBuffalo** [comment]
The update messed up the spacing in the left panel.

![Screenshot_20221215_115712](https://user-images.githubusercontent.com/87632612/207788585-5c71ac54-b7f4-408c-bb7b-81ca37710d5f.png)

Expected Behaviour:
![Screenshot_20221215_115630](https://user-images.githubusercontent.com/87632612/207788654-4662cc2d-5489-4f50-baae-b7b0d59a936b.png)

**Comment by harbassan** [comment]
Go into your sidebar config and unstick the liked songs and new playlist button.
