### ISSUE TITLE
[Dribblish] Seeker entirely disappeared

### ISSUE THREAD

**Issue by Potato22** [spicetify/spicetify-themes#877]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version.
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
The seeker is nowhere to be seen upon installing the theme.

Although there is an odd bug that has been going on for months now, every time I touched the seeker it just skips the song entirely for no reason. I can't see anyone else having this problem. (Might be a factor?)

**To Reproduce**
1. Install Dribbblish: `spicetify config current_theme dribbblish color_scheme dark ; spicetify apply`
2. Observe

**Expected behavior**
The seeker should be visible

**Screenshots**
![image](https://user-images.githubusercontent.com/39096741/207504433-096799d7-6cab-448c-9519-e1a9b8e807ca.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_CONNECTION_TIMED_OUT
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_CONNECTION_TIMED_OUT
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-hpto.js.map: Connection error: net::ERR_CONNECTION_TIMED_OUT
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/7370.js.map: Connection error: net::ERR_CONNECTION_TIMED_OUT
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_CONNECTION_TIMED_OUT
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/616.js.map: Connection error: net::ERR_CONNECTION_TIMED_OUT
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-v2.js.map: Load canceled due to load timeout
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/55.js.map: Load canceled due to load timeout
```

**Specifics (please complete the following information):**
 - OS: W11 Pro for Workstation 22H2 build: 22623.1028
 - Spotify version 1.2.0.1165.gabf054ab
 - Spicetify version v2.14.3
 - Theme name Dribbblish/dark

**Comment by harbassan** [comment]
When did you install the theme exactly? I've just updated it so could you re-install it from the repo and then let me know whether the bug is still there or not.

**Comment by Potato22** [comment]
![Spotify_5S353zQyg9](https://user-images.githubusercontent.com/39096741/208013114-4e3c58af-e749-47e0-b76f-23eb7af697b9.png)
nothing seemed to change, even after reinstalling.

**Comment by harbassan** [comment]
Make sure you've added the `dribbblish.js` file into the extensions folder and then added it to the config using the command `spicetify config extensions dribbblish.js`. Then run `spicetify apply`.
