### ISSUE TITLE
[Dribbblish] Misaligned sidebar playlist icons

### ISSUE THREAD

**Issue by k1gen** [spicetify/spicetify-themes#879]
![image](https://user-images.githubusercontent.com/62500387/210181955-ded9fd12-f902-4440-864f-8c8765aa8e3e.png)

**Comment by stpnwf** [comment]
Also have this issue on a brand new install using Marketplace: 
![Screenshot from 2023-01-04 16-45-44](https://user-images.githubusercontent.com/81482539/210612237-5557a46d-b1e1-4b4c-ba65-ac880a933713.png)

**Comment by bhubneshmaharana** [comment]
Sir i want to work on this issue,can u pls guide me through
