### ISSUE TITLE
[Dribbblish] UI breaks

### ISSUE THREAD

**Issue by stpnwf** [spicetify/spicetify-themes#880]
**Describe the bug**
UI breakages on brand new setup using marketplace

**To Reproduce**
1. Install Spotify from Flathub (ver )
2. install Spicetify and Marketplace from one line Linux shell scripts in [Getting Started page](https://spicetify.app/docs/getting-started)
3. Install Dribblish
4. See breaks

**Screenshots**

![Screenshot from 2023-01-04 16-42-11](https://user-images.githubusercontent.com/81482539/210612876-6b58cd68-9de4-4d87-914b-aa0b84cad915.png)
![Screenshot from 2023-01-04 16-18-17](https://user-images.githubusercontent.com/81482539/210612882-f216ee14-45d2-4289-92e8-19af787e9d4c.png)

**Specifics (please complete the following information):**
 - OS: VanillaOS
 - Spotify version 1.1.84.716.gc5f8b819
 - Spicetify version: 2.16.0
 - Theme name: Dribbblish

**Comment by harbassan** [comment]
The reason for this is that your spotify version is out of date with the current version of the theme. You can either just upgrade or you can wait and ill try and make a fix for the older spotify vers.
