### ISSUE TITLE
[Dribblish]  cant see friend activity

### ISSUE THREAD

**Issue by toprak** [spicetify/spicetify-themes#887]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version.
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
It does not show friend activity just blank
**To Reproduce**
1. Go to 'open spotify'

**Expected behavior**
see what my friend listening
**Screenshots**
![Screenshot_2023-02-12_07-22-58](https://user-images.githubusercontent.com/43301560/218292902-d879aebb-f778-4d10-9fcf-9268f4a23a5f.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.
dev tools does not open I did everything above
```console
[libprotobuf ERROR ../core/vendor/protobuf3/src/google/protobuf/wire_format_lite.cc:577] String field 'spotify.event_sender.proto.DroppedEvents.DroppedEventsBySequenceIdEntry.key' contains invalid UTF-8 data when parsing a protocol buffer. Use the 'bytes' type if you intend to send raw bytes. İTS FROM TERMINAL
```

**Specifics (please complete the following information):**
 - OS: Debian bullseye
  - Spotify version [e.spotify-client is already the newest version (1:1.1.84.716.gc5f8b819-2).]
 - Spicetify version [2.16.1]
 - Theme name Dribblish rose pine

**Comment by harbassan** [comment]
ill check it out

**Comment by harbassan** [comment]
you're gonna need to get your devtools working or else I have no clue why its doing that.

**Comment by harbassan** [comment]
Updating spotify should fix this.

**Comment by toprak** [comment]
@harbassan spotify is already latest version on debian repo so yeah
`spotify-client is already the newest version (1:1.1.84.716.gc5f8b819-2).`
