### ISSUE TITLE
[dribbblish] ui theme broken

### ISSUE THREAD

**Issue by marione44** [spicetify/spicetify-themes#892]
**Prerequisites**
Os: Ubuntu 20.04
Spicetify version: 2.16.1
Spotify version: 1.1.84.716.gc5f8b819

**Describe the bug**
nowPlayingBar doesnt follow the lenght of its container. I installed many times spicetify and spotify but the ui wont fix.
I tried all the color schemes but the problem persist. Out of curiosity i tried to dribblish dynamic and everything is working fine.

**Screenshots**
![ui](https://user-images.githubusercontent.com/79664817/221047264-b7defe94-e536-41b1-9a6d-31dfb82e353f.png)

**Logs**
[config-xpui.txt](https://github.com/spicetify/spicetify-themes/files/10819161/config-xpui.txt)

console log
![log](https://user-images.githubusercontent.com/79664817/221047416-8a1cef88-1494-4af2-9a9c-a47abfc38988.png)

**Comment by the-argus** [comment]
I have the same issue. Pretty sure most of these themes need to be updated to the new spotify version for linux and will remain broken until then.

**Comment by the-argus** [comment]
![image](https://github.com/spicetify/spicetify-themes/assets/70479099/8b1a130c-7d33-43a5-9592-51aaa6bce6c8)
this is not resolved, as far as I can tell. Why did you close it, @harbassan ?
