### ISSUE TITLE
[Dribbblish] Menu, home, playlists, playlist images, etc. won't appear

### ISSUE THREAD

**Issue by piongpiong00** [spicetify/spicetify-themes#893]
Almost the same problem as someone from the closed issues, except their solution--to toggle the view of friends activity--does not work for me. The menu is there but the view is very small that it is almost not there.

I tried opening and closing spotify but nothing happens. I also tried to open and close the friends activity section but it only adds an empty space to where it should appear. I tried to scroll in the inbetween area where the menu should show up, and I can see ads and only title texts like "Settings" while the rest of the text is not visible.

No menu while friends activity is on:
![image](https://user-images.githubusercontent.com/126226809/221103634-f670129a-b50e-47bb-91cd-1b0691e951eb.png)

Tiny glimpse of an ad in the menu:
![image](https://user-images.githubusercontent.com/126226809/221104228-4a45ba67-f99b-42c6-85ec-8aea907c4463.png)

![image](https://user-images.githubusercontent.com/126226809/221104746-65754752-4015-4298-a952-a6ddad3e5fcc.png)

 - OS: Windows v10.0.22621
 - Spotify v1.2.5.1006
 - Spicetify v2.7.3
 - Dribbblish v4.2.2-8da36b8

**Comment by harbassan** [comment]
try removing your installed extensions, specifically whatever you have installed that is related to folders.

**Comment by SuperHackerKev** [comment]
got the same display error.

**Comment by harbassan** [comment]
Ah i see now, you're using dribblish dynamic, which is an older theme that is no longer being maintained. You need to install normal dribbblish instead (from this repo or marketplace). If you want to get the same "dynamic" part you can use marketplace's dynamic colours setting.
