### ISSUE TITLE
[Dribbblish] Can't remove window controls

### ISSUE THREAD

**Issue by schnotzler** [spicetify/spicetify-themes#902]
**Describe the bug**
I can't get the window controls to vanish in Windows 10

**To Reproduce**
1. Use Dribbblish Theme
2. start spotify with `--transparent-window-controls` flag, or any of the 3 SpotifyNoControl.exe variants listed [here](https://github.com/spicetify/spicetify-themes/tree/master/_Extra/SpotifyNoControl)
3. Observe that the controls are still there

**Expected behavior**
Window controls are gone

**Screenshots**
![image](https://user-images.githubusercontent.com/23164797/225419919-5d82f890-c15a-4361-af8d-6b268ddedae4.png)

**Specifics :**
 - OS: Win10
 - Spotify version: 1.2.7.1277.g2b3ce637
 - Spicetify version: v2.16.2
 - Dribbblish

**Comment by harbassan** [comment]
Yeah its actually not possible to remove the windows controls completely, the only thing those flags do is make it slightly transparent.

**Comment by schnotzler** [comment]
Thanks for your response. Unfortunately i could not observe this change in transparency you mentioned at all.

In my _short_ testing is could not find any difference if i launch Spotify with or without the flag whatsoever.

This screenshot was taken WITHOUT the `--transparent-window-controls` launch flag:
![No flag](https://user-images.githubusercontent.com/23164797/225797097-010751eb-459d-444f-99aa-36679aa2115e.PNG)

This screenshot was taken WITH the `--transparent-window-controls` launch flag:
![flag](https://user-images.githubusercontent.com/23164797/225797417-98b00936-2d69-48aa-9795-960ca0e8af56.PNG)

The theme i used in both screenshots is `Dribbblish` -> `dracula` btw.  Maybe this matters?

Both configurations show identical HEX color codes for the window controls, so maybe the flag currently has no function at all/ is broken? 

Can you @harbassan or anyone else reproduce the `--transparent-window-controls` flag having **no** effect on their setup?

**Comment by harbassan** [comment]
oh yeah i just realised the flag is now actually redundant because the controls are now automatically transparent. They used to have a purpose as the default was solid but now they do nothing. Unfortunately what you have is as good as it can be.
