### ISSUE TITLE
[BurntSienna] Top Icon Spacing Messed Up 

### ISSUE THREAD

**Issue by jimmysofat6864** [spicetify/spicetify-themes#903]
**Describe the bug**
Top icon spacing looks off and has gaps. And some of the icons look squished. Large spacing in friends section compared to before. 

**To Reproduce**
1. Install BurntSienna Theme

**Expected behavior**
Buttons and search bar aren't' supposed to look cut off and squished and have adequate spacing. Applies to friends' section as well. Also, odd spacing between your library and the back and forward buttons that also look off-center and out of place. 

**Screenshots**
<img width="1279" alt="Screenshot 2023-03-16 172224" src="https://user-images.githubusercontent.com/69532417/225781217-5da0a215-3043-46c2-90d0-724c25ca1b71.png">

**Specifics (please complete the following information):**
Windows 11
Spotify for Windows
Version 1.2.7.1277.g2b3ce637
Spicetify v2.16.2
Burnt Sienna

**Comment by harbassan** [comment]
This theme is pretty outdated (because no-one maintains it anymore), and therefore doesnt support any of the new layout. You're gonna need to go into experimental features and disable the new home layout option to get it looking normal.

**Comment by pjaspinski** [comment]
Thank you for reporting this issue. I haven't had much time recently to update this theme to work with Spotify's new layout, but I'm planning on doing it in near future. A PR fixing this issue is always welcome :)
