### ISSUE TITLE
[Dribbblish] Can't resize the buddy feed / right sidebar 

### ISSUE THREAD

**Issue by LILCOOTS** [spicetify/spicetify-themes#905]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version.
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
I can not resize the right sidebar/buddy feed to hide the text.

**To Reproduce**
1. Install Dribbblish.
2. Click on sidebar.
3. Try and drag mouse to change sidebar size.

**Expected behavior**
The Right sidebar/ Buddy Feed should be able to size down to show only icons and hide the text like the Left sidebar/ Navbar.

**Screenshots**

![Screenshot](https://user-images.githubusercontent.com/112123021/227742418-f65e6d21-44c3-4038-b350-1fcddd051857.png)
https://drive.google.com/file/d/13q0h7-u9g-CIMhwO-kuWfomeEqXvb9or/view?usp=sharing

 - OS: Windows 11
 - Spotify version: 1.2.7.1277.g2b3ce637
 - Spicetify version: v2.16.2
 - Theme name: Dribbblish

**Comment by oneeyedreaper** [comment]
Had the same issue for a couple of days, but now the right sidebar is just blank on dribbblish. Works fine on other themes.

Dribbblish ⬇⬇⬇
![image](https://user-images.githubusercontent.com/53879034/231150561-39075991-32de-4c47-94ad-f7174bea1479.png)

Ziro ⬇⬇⬇
![image](https://user-images.githubusercontent.com/53879034/231150527-12ea873a-3bde-4a81-a76d-44a692bbb60d.png)

**Comment by oneeyedreaper** [comment]
UPDATE: Tried a clean spicetify-cli reinstall with Dribbblish and had the same results.

**Comment by oneeyedreaper** [comment]
@harbassan Reencountered this issue today. Even after a clean reinstall, the issue's still persistent. Can you confirm if it's worth reopening this issue or if it is just a problem on my side?
