### ISSUE TITLE
Can't Apply Theme

### ISSUE THREAD

**Issue by Ayaan2312** [spicetify/spicetify-themes#910]
So, I wanted to apply the Ziro Purple Dark theme but due to some reasons It just gives me the Black and White theme of Ziro, I used this powershell code - spicetify config current_theme Ziro color_scheme Purple Dark. If it is wrong however please tell me the right as it is not mentioned in the file

**Comment by vatana7** [comment]
I was having the same problem applying Ziro theme for Spicetify as well. The UI doesn't even work correctly

**Comment by hhhhibiki** [comment]
so am i

**Comment by harbassan** [comment]
the correct command is `spicetify config color_scheme purple-dark`. The same rule applies for any multiple word color scheme.

**Comment by fc8CIvmLkQyHJic** [comment]
For Rosé Pine Moon command is `spicetify config color_scheme Rose-Pine-Moon`. It is the same for Rosé Pine Dawn as well.

**Comment by harbassan** [comment]
The color schemes are not case-sensitive.

**Comment by fc8CIvmLkQyHJic** [comment]
Yes, you are right, thank you for correct that
