### ISSUE TITLE
[Dribbblish Rose Pine] Active tab color is the same as text color

### ISSUE THREAD

**Issue by JAWalmsley** [spicetify/spicetify-themes#918]
I'm just opening this so I can send in a fix for it in like 5 mins :)

**Describe the bug**
The `--spice-tab-active` color is the same as the `spice-text` color, meaning text on the active tab (and modals) is illegible.

**To Reproduce**
1. Set theme to rose pine
2. Open "Your Library" tab
3. The "playlists" tab can not be read because the colors are the same

**Expected behavior**
Text should be legible

**Screenshots**
![image](https://user-images.githubusercontent.com/35351784/233811664-581b8788-4895-4519-bdf3-b3976efbd46e.png)

**Logs**
Probably not necessary here

**Specifics (please complete the following information):**
 - OS: Windows
 - Spotify version 1.1.96.785.g464c973a
 - Spicetify version 2.17.0
 - Theme name: Dribbblish Rose Pine

**Comment by the-argus** [comment]
thanks for fixing my theme :)
adding it to my config
