### ISSUE TITLE
[Dribbblish] The touchpad can allow the page to be scrolled horizontally.

### ISSUE THREAD

**Issue by Lucas-TY** [spicetify/spicetify-themes#920]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version. 
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**

Swiping left or right on the touchpad will change the position of the root container.

**To Reproduce**

**Expected behavior**

Root-container's position to be fixed

**Screenshots**
![image](https://user-images.githubusercontent.com/48132189/234378077-d176e966-6e69-4e88-941a-a9f6d37db79b.png)

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

![image](https://user-images.githubusercontent.com/48132189/234382803-edd9025f-0efc-4204-83d4-1d908d2012d7.png)

**Specifics (please complete the following information):**
 - OS: windows11
 - Spotify version 1.2.9.743.g85d9593d
 - Spicetify version v2.17.2
 - Theme name Dribbblish

**Comment by Lucas-TY** [comment]
just created a pull request for this

**Comment by harbassan** [comment]
i'm pretty sure there's an reason for this that involves the friends feed, so it would be better to fix that issue directly rather then doing a quick fix like this.
