### ISSUE TITLE
Sleek UltraBlack (UI is not changed as shown in the preview)

### ISSUE THREAD

**Issue by GXTCKU** [spicetify/spicetify-themes#927]
I'm using [EndeavourOS Arch based] 

preview of the theme 
![ultrablack](https://user-images.githubusercontent.com/128229952/236636744-a1eb366a-015a-49e3-83d9-e1ab3c0ce78e.png)

preview of the theme applied 
![Screenshot](https://user-images.githubusercontent.com/128229952/236636706-f7d34589-7a08-4e61-a959-50edd3df3a71.png)

I'm using the latest version of spotify and spicetify 
Would be a great help on fixing this issue 

ThanYou
fellow spicetify user

**Comment by MGPlayzYT** [comment]
it seems to be working as intended? unless you mean the sidebar, then that's an entirely different thing. it's the new "Your Library" view Spotify introduced in newer versions.

**Comment by harbassan** [comment]
yep pretty much. If you want to revert to the old sidebar go into experimental features and untick 'your library x view of the left sidebar'

**Comment by GXTCKU** [comment]
> it seems to be working as intended? unless you mean the sidebar,

Yeah, my bad didn't mention that

**Comment by GXTCKU** [comment]
Thanks mate issue solved
