### ISSUE TITLE
[Turntable] Spicetify returns ambiguous "Err" in console upon applying, while also no turntable animations.

### ISSUE THREAD

**Issue by Potato22** [spicetify/spicetify-themes#929]
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version. ✅
2. Your Spotify version is compatible with the `spicetify` version you are using. ✅
3. You have the most recent version of the themes. ✅ **(git re-cloned 2 days ago)**
4. You followed the installation instructions for the theme you use (please review the entire theme README). ✅

**Describe the bug**
While inside the console, applying the `Turntable` theme returns an **ambiguous "Err"** but still proceeds with the `apply`.
None of the turntable animations is working, the now playing image is static.

**To Reproduce**
1. Apply Turntable
2. See `Err` in the console while it still successfully applies
3. Play any song.
4. Image stays static.

**Expected behavior**

**Screenshots**

https://github.com/spicetify/spicetify-themes/assets/39096741/85c3a64e-9f74-48a9-839f-8513723369ba

https://github.com/spicetify/spicetify-themes/assets/39096741/e95e5d1f-3478-47ca-98b2-50fdc7cc3f26

![image](https://github.com/spicetify/spicetify-themes/assets/39096741/c64bc622-281c-46c2-89e7-14600ffd112a)
![image](https://github.com/spicetify/spicetify-themes/assets/39096741/0b12653f-1949-473b-bb80-14e2ac9c4919)

**Logs**
```console
cosmos-connector:  fetchAdForSlot endpoint=%o sp://ads/v1/ads/hpto
gae2-spclient.spotify.com/remote-config-resolver/v3/configuration:1          Failed to load resource: the server responded with a status of 404 ()
vendor~xpui.js:29 provider:transport resolve error T Object
m @ vendor~xpui.js:29
index.html:1 Uncaught (in promise) T
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/vendor~xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/950.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-hpto.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/714.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-desktop-modals.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/4577.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/home-v2.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2029300)
    at onSuccess (xpui.js:1:2029114)
onError @ vendor~xpui.js:29
h @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/3969.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
DevTools failed to load source map: Could not load content for https://xpui.app.spotify.com/xpui-routes-collection-songs.js.map: Connection error: net::ERR_NAME_NOT_RESOLVED
vendor~xpui.js:29 NotFoundError: GET request to sp://core-playlist/v1/playlist/spotify%3Aplaylist%3A37i9dQZF1EYkqdzj48dyYq/?responseFormat=protobufJson&start=0&length=0 failed with status code 404
    at l.onSuccess (xpui.js:1:2029300)
    at onSuccess (xpui.js:1:2029114)
onError @ vendor~xpui.js:29
h @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
Promise.then (async)
(anonymous) @ vendor~xpui.js:29
Promise.catch (async)
l @ vendor~xpui.js:29
u @ vendor~xpui.js:29
t.fetch @ vendor~xpui.js:29
n.executeFetch @ vendor~xpui.js:29
n.fetch @ vendor~xpui.js:29
n.refetch @ vendor~xpui.js:29
t.onFocus @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
t.batch @ vendor~xpui.js:29
n.onFocus @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
n.onFocus @ vendor~xpui.js:29
(anonymous) @ vendor~xpui.js:29
n @ vendor~xpui.js:29
```

**Specifics (please complete the following information):**
 - OS: Windows11 Pro for Workstation 22H2 - Build 22624.1690
 - Spotify version
 ```
 Spotify for Windows
1.2.10.760.g52970952
```
 - Spicetify version [e.g. 1.1.0] `Spicetify v2.18.1`
 - Theme Name `Turntable`

**Comment by harbassan** [comment]
was it working fine a week ago?

**Comment by P-Ramos16** [comment]
Same here on Manjaro Linux, seems like inject_theme_js throws a "Not a valid field" warning when we try to change its config value to 1. All other configs (inject_css, replace_colors, overwrite_assets, etc) work fine.
Did its name change? Also to me the play/skip/etc icons and the rest of the music info don't show. Not sure if related or not since it shows in Potato22's screenshots.

![2023-06-18_11-17](https://github.com/spicetify/spicetify-themes/assets/98025083/488cd8bd-ef5d-45df-aa0f-dcca4ac789c6)

![2023-06-18_11-22](https://github.com/spicetify/spicetify-themes/assets/98025083/aec1a3e4-343d-41d0-9078-d24de377bdb1)

**Comment by harbassan** [comment]
you could try just entering it manually into the config file, but it should be enabled by default anyway i think. As for the rest, ill try to fix it when I get time.

**Comment by P-Ramos16** [comment]
Can confirm, it's fixed! Thank you very much.
