### ISSUE TITLE
[Ziro] Volume bar out of line

### ISSUE THREAD

**Issue by ianz56** [spicetify/spicetify-themes#933]
![image](https://github.com/spicetify/spicetify-themes/assets/41635087/ded9a0a9-43b6-4c23-9bca-e0671e373d4d)

The volume bar goes out of line when another device is playing.

**Comment by IzzatHaikal** [comment]
I've checked and I think this is related to this PR #916 . @harbassan can we possibly remove the older version part?

**Comment by harbassan** [comment]
if you're sure that that specific line is causing it (test it with and without that line), then if you open a pr I'll approve it.
