### ISSUE TITLE
Any theme that works with the new Library X UI?

### ISSUE THREAD

**Issue by DimitrisMilonopoulos** [spicetify/spicetify-themes#936]
Can't seem to find a theme that has documented support, so if you know any that would be great!

**Comment by iTenerai** [comment]
Currently using the Nightlight theme which seems to work well with the new UI. Other themes not tested but I believe that there are surely more that work.

**Comment by harbassan** [comment]
not many work with it yet, but there are a few, like Matte which just updated. Dribbblish support for it will be coming soon aswell hopefully.
