### ISSUE TITLE
[Dribbblish] Can't set image on folders after update

### ISSUE THREAD

**Issue by erenseekingfreedom** [spicetify/spicetify-themes#943]
After the latest update, I can't set an image as the background for folders with the Dribbblish theme. I'm running Spotify Version 1.2.12.902.g1924b088 on MacOS and Spicetify v2.19.0.

**Comment by harbassan** [comment]
will look into it

**Comment by harbassan** [comment]
i've now re-implemented it into the latest version of the theme
