### ISSUE TITLE
[Dribbblish] Seekbar in the wrong position and overflowing.

### ISSUE THREAD

**Issue by kaevm** [spicetify/spicetify-themes#948]
![image](https://github.com/spicetify/spicetify-themes/assets/100613244/dc996dd2-5c29-43cc-80e2-472eb6192015)

**Comment by harbassan** [comment]
currently dribblish doesnt have ylx support, so if you go into the experimental features and dsiable ylx, it should work normally.

**Comment by 1-minute-to-midnight** [comment]
How is this done? I have looked for ylx in the Dribbblish folder but I can't seem to find it

**Comment by harbassan** [comment]
in experimental features in spotify, which you can access by clicking on your profile icon
