### ISSUE TITLE
[Blossom] Screen off centered

### ISSUE THREAD

**Issue by LoganWolfie** [spicetify/spicetify-themes#952]
The screen becomes off centered after clicking on the lyrics button. 

![image](https://github.com/spicetify/spicetify-themes/assets/72407034/dad4a4d6-2ace-4fac-9e80-9e5501514f8b)

**Comment by harbassan** [comment]
im not getting this issue anymore, mustve fixed itself with the spotify update

**Comment by LoganWolfie** [comment]
> im not getting this issue anymore, mustve fixed itself with the spotify update

im still getting it even after the update.

![image](https://github.com/spicetify/spicetify-themes/assets/72407034/378ea8e4-7ea2-42c2-87c0-da2ce5b21521)

**Comment by Robatortas** [comment]
I haven't looked at the code in the theme in a while, but I am most probably guessing it is a bug with the screen resolution..

**Comment by LoganWolfie** [comment]
![image](https://github.com/spicetify/spicetify-themes/assets/72407034/71a20e62-f7fe-42f1-8961-75b9441f7768)

after the new spotify update with the ui change it now dosent go back all the way.

**Comment by Robatortas** [comment]
![image](https://github.com/spicetify/spicetify-themes/assets/72624799/a7302e0c-22a1-424f-a66d-83433e1523c0)
![image](https://github.com/spicetify/spicetify-themes/assets/72624799/6a7dbfef-c430-4738-84c7-18ca03cfb497)


I am kinda sure that is just a spotify thing, with spotify without any modifications it has a space on the left, just like with the theme.

**Comment by Robatortas** [comment]
And that also depends on the screen size, for example, on a 1080p monitor, it looks like this.
![image](https://github.com/spicetify/spicetify-themes/assets/72624799/08499653-2460-4c48-9907-809a02e4f692)

And with 1440p it looks like this:
![image](https://github.com/spicetify/spicetify-themes/assets/72624799/8a8c98a1-647c-4e6a-b141-d4ad03455e0a)

So the size is fixated basically.. Let me check if I can change that.

**Comment by LoganWolfie** [comment]
no you guys are not gettingt it. you need to click the **lyrics** button first
