### ISSUE TITLE
[Dreary] 

### ISSUE THREAD

**Issue by OrionsStarr** [spicetify/spicetify-themes#959]
Playlists on side bar off center. Border merging with main section (sidebar config was ineffective).
 Play/Pause button filled with multiple icons instead of 1. 
The line at the top of playlist display goes beyond the border.
 The shuffle, loop, and skip buttons are dark red instead of white so they almost blend in with the background color.

**Comment by harbassan** [comment]
Unfortunately dreary is no longer being maintained. If you do really like it i suggest doing the fixes yourself with some basic css, otherwise just use something else.
