### ISSUE TITLE
spotify blank / shows error in powershell 

### ISSUE THREAD

**Issue by eclipse-was-imagined** [spicetify/spicetify-themes#964]
![Screenshot 2023-06-28 221254](https://github.com/spicetify/spicetify-themes/assets/104556984/7223dd7b-0516-4633-9332-ad99a6e11630)
**Prerequisites**
Before opening an issue, make sure
1. You have the most recent `spicetify` version.
2. Your Spotify version is compatible with the `spicetify` version you are using.
3. You have the most recent version of the themes.
4. You followed the installation instructions for the theme you are using (please go through the entire theme README).

**Describe the bug**
I am not sure if its a bug but I have been using spiceitfy for an yr or more and I haven't faced any issues till date but just today It throws up an error and even after flowing powershell instructions to proceed spotify shows me a clear black screen and nothing else 

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
Add logs from console. To do that
1. Run `spicetify enable-devtools` in terminal
2. Spotify will be restarted
3. Hit <kbd>Ctrl + Shift + I</kbd> to open DevTools window
4. Navigate to tab Console
5. Copy console window content.

```console
(Please paste here console logs or attach a screenshot)
```

**Specifics (please complete the following information):**
 - Spotify version [e.g. 1.1.10.546.ge08ef575]
 - Spicetify version [e.g. 1.1.0]
 - Theme name

**Comment by harbassan** [comment]
read the message. Reinstall spotify and then run the command.

**Comment by eclipse-was-imagined** [comment]
I did tried re-installing thrice and then if I run command it shows Spotify spiced up , and when I open the app it just shows me a black screen and if I do spicetify apply again it shows the above error

**Comment by harbassan** [comment]
try making an issue on the spicetify-cli repo because i don't know.
