### ISSUE TITLE
[Dribblish] Broken UI.

### ISSUE THREAD

**Issue by soudblox** [spicetify/spicetify-themes#966]
Spicetify version: v2.20.3
Spotify version: 1.2.14.1149.ga3ae422d
Installed from marketplace.

![image](https://github.com/spicetify/spicetify-themes/assets/73058244/e2363627-7dec-4d14-964e-a11d43f377c3)

**Comment by MonsieurDupont** [comment]
same problem here, last fix didn't work

**Comment by hanashi17** [comment]
yeah deadass how do yall manage to fuck smth up every update, like no changes were needed before yall started fuckin it up
are you guys new to this?

**Comment by harbassan** [comment]
> 

fix it yourself dumbass

**Comment by hanashi17** [comment]
> fix it yourself dumbass

LOL ur jus mad ur shit is ass bro get good

**Comment by rgndxzzk** [comment]
> > fix it yourself dumbass
> 
> LOL ur jus mad ur shit is ass bro get good

i will tear off your face and wear it

**Comment by harbassan** [comment]
should be fixed now, give it a few hours to update on marketplace
