### ISSUE TITLE
[Blossom] Off Centered (explained better)

### ISSUE THREAD

**Issue by LoganWolfie** [spicetify/spicetify-themes#968]
im not sure if anyone saw my new comment i made about 5 days ago but it only becomes off-centered after you go into the "lyrics" section of spotify. 

you can almost fix it all the way by hovering over the play bar but it will go back if you are still in the lyrics section.
and yes im on 1080p and i noticed you tested it but i dont think anyone saw that i mentioned the lyrics section.

![Screenshot 2023-07-06 013544](https://github.com/spicetify/spicetify-themes/assets/72407034/e76542a6-b1a7-4a31-a68b-809f5739e2af)
![image](https://github.com/spicetify/spicetify-themes/assets/72407034/47a928f6-bd23-4bed-a373-22834e1d1faf)

**Comment by harbassan** [comment]
I did click on the lyrics button but I literally cannot replicate the issue. Ill try again later maybe.

**Comment by LoganWolfie** [comment]
im not sure then cause it only happens on blossom and when i turn it off it dosent. 
maybe its just glitched with a plugin?
