### ISSUE TITLE
[dribblish] messed up ui

### ISSUE THREAD

**Issue by TrashieCan** [spicetify/spicetify-themes#969]
the ui is screwed, id like to be able to see my playlists and everthing else, is there a way i can uninstall the them without the need to access the marketplace CAUSE I CANT ACCESS IT.
![image_2023-07-11_152637549](https://github.com/spicetify/spicetify-themes/assets/139279821/5603cc91-7da1-4f27-ae3e-0eef7d353e24)

**Comment by todayisyokult** [comment]
I used this theme yesterday and also had the same problem.It ook me an hour to solve it yesterday. You can try to re-execute another theme in the code window, and then go to the market to apply another theme while the theme is in effect. Because the code window will change to the dribblish interface in a few seconds after applying the new theme directly, so you need to go to the market to apply another theme. hope it can help you

**Comment by dorkomorko** [comment]
> I used this theme yesterday and also had the same problem.It ook me an hour to solve it yesterday. You can try to re-execute another theme in the code window, and then go to the market to apply another theme while the theme is in effect. Because the code window will change to the dribblish interface in a few seconds after applying the new theme directly, so you need to go to the market to apply another theme. hope it can help you

Could you explain this a bit better, every time I run the theme config command it just says it's an invalid theme and I have no other way of removing this theme to access any other part of my spotify which means that spicetify itself is useless to me now

**Comment by todayisyokult** [comment]
> > 我昨天用了这个主题，也遇到了同样的问题。昨天花了我一个小时才解决。您可以尝试在代码窗口中重新执行另一个主题，然后在主题生效期间去市场应用另一个主题。因为直接应用新主题后几秒后代码窗口就会变成dribblish界面，所以需要去市场应用另一个主题。希望它能帮助你
> 
> 你能解释得更好一点吗，每次我运行主题配置命令时，它只是说这是一个无效主题，而且我没有其他方法可以删除这个主题以访问我的 Spotify 的任何其他部分，这意味着 SPECETIFY 本身对我来说毫无用处现在

————————
I installed another theme in iTerm(named nord theme), and then the app automatically changed to the nord theme, but after a few seconds, it switched back to the Dribbblish theme. So, during those few seconds, I quickly opened the marketplace and changed to another marketplace theme, and then it returned to normal. you can try this ,Windows  use Powershell, MacOS use iterm .
for example run this theme
"curl -fsSL https://raw.githubusercontent.com/Tetrax-10/Nord-Spotify/master/install-scripts/install.sh | sh"

**Comment by todayisyokult** [comment]
> > I used this theme yesterday and also had the same problem.It ook me an hour to solve it yesterday. You can try to re-execute another theme in the code window, and then go to the market to apply another theme while the theme is in effect. Because the code window will change to the dribblish interface in a few seconds after applying the new theme directly, so you need to go to the market to apply another theme. hope it can help you
> 
> Could you explain this a bit better, every time I run the theme config command it just says it's an invalid theme and I have no other way of removing this theme to access any other part of my spotify which means that spicetify itself is useless to me now

I installed another theme in iTerm(named nord theme), and then the app automatically changed to the nord theme, but after a few seconds, it switched back to the Dribbblish theme. So, during those few seconds, I quickly opened the marketplace and changed to another marketplace theme, and then it returned to normal. you can try this ,Windows use Powershell, MacOS use iterm .
for example run this theme
"curl -fsSL https://raw.githubusercontent.com/Tetrax-10/Nord-Spotify/master/install-scripts/install.sh | sh"

**Comment by TrashieCan** [comment]
i uninstalled spicetify and spotify and reinstalled and it fixed easily

**Comment by dorkomorko** [comment]
> i uninstalled spicetify and spotify and reinstalled and it fixed easily

tried it a few times and didn't work for me so I'm not sure tbh, just hoping they'll remove or fix the theme

**Comment by stealingudc** [comment]
Same here after installing through Marketplace. Modifying config-xpui.ini, either through the CLI or manually, does not change the theme. Not sure whether it's an issue with the CLI, Marketplace, or Dribblish. At this point, Spicetify is completely unusable to me.

**Comment by harbassan** [comment]
should be fixed in a few hours max
