### ISSUE TITLE
[Theme-name] text

### ISSUE THREAD

**Issue by todayisyokult** [spicetify/spicetify-themes#974]
The icon size of local files is different from other lists.

 ** screenshot **
 
![image](https://github.com/spicetify/spicetify-themes/assets/125634462/1baa94b4-552b-4244-bcdb-def3a1ac2948)

**Specifics **
 - Spotify for macOS (Apple Silicon) 1.2.15.828.g79f41970
 - Spicetify v2.20.3
 - Theme: text / Kanagawa

**Comment by todayisyokult** [comment]
and How can I display the image of a playlist?

 thaks a lot

**Comment by darkthemer** [comment]
Once the pull request is merged, you can edit which part of the UI displays the image.
More details in README
