### ISSUE TITLE
[Dribbblish] - Volume bar and icons not visible due to lack of contrast colors and Dropdown texts almost no visible

### ISSUE THREAD

**Issue by Miguel22247** [spicetify/spicetify-themes#983]
## **Describe the bug**
If you look closely to the bar using the following Colors

- Base
- dark
- samurai

you will notice that on some of this color settings the icons are almost no visible (case of Samurai) in the other ones the volume bar is not noticable, also if you go to settings the color of the text in the dropdowns have little contrast to the background **(this happens to all color settings)**

**Note:** On samurai color theme the colors of the texts of the marketplace and "Upgrade or Explore Premium" are not visible

## **To Reproduce**
- Install Dribbblish theme
- You can Notice in some color settings like Base that the volume bar/icons is not visible

## **Expected behavior**
That the icons could see correctly

## **Screenshots**

- Text of the dropdowns 

![image](https://github.com/spicetify/spicetify-themes/assets/66649043/2ee2111a-8960-475c-b491-b24e30204e2b)
- Volume bar

![image](https://github.com/spicetify/spicetify-themes/assets/66649043/8981edb4-e743-49c7-a720-772d6d90b105)

- Icons on samurai color
![image](https://github.com/spicetify/spicetify-themes/assets/66649043/853c6c7c-760e-47ba-8b0f-3d09ae1ba816)
![image](https://github.com/spicetify/spicetify-themes/assets/66649043/0699206e-bad7-4ae2-a509-ffe384cfcf5a)

## **Specifics (please complete the following information):**
 - OS: Spotify for Windows (64 bit)
 - Spotify version: 1.2.16.947.gcfbaa410
 - Spicetify version: 2.22.1
 - Dribbblish

**Comment by harbassan** [comment]
i'll get to this soon
