### ISSUE TITLE
Unable to switch color scheme using Sleek theme

### ISSUE THREAD

**Issue by aphextwinning** [spicetify/spicetify-themes#991]
**Prerequisites**
Before opening an issue, make sure ✅
1. You have the most recent `spicetify` version. ✅
2. Your Spotify version is compatible with the `spicetify` version you are using. ✅
3. You have the most recent version of the themes. ✅
4. You followed the installation instructions for the theme you are using (please go through the entire theme README). ✅

**Describe the bug**
When I execute the commands listed in the Sleek theme README on Windows Powershell, the color scheme (not the theme, the theme works fine!) stays as the default.
`spicetify config color_scheme <scheme name>`
`spicetify apply`
I want the BladeRunner color scheme but no matter how I write it, it doesn't change. I've tried the command below in this case.
`spicetify config color_scheme BladeRunner`
`spicetify apply`
I've also noticed an Err message, shown below.

**Expected behavior**
The color scheme would change to the right one.

**Console/Screenshot**
![imagen](https://github.com/spicetify/spicetify-themes/assets/130928236/be110070-ce12-419b-85e9-d57accbf592a)

**Specifics (please complete the following information):**
 - OS: Windows 10 (64 bits)
 - Spotify version 1.2.18.999.g9b38fc27
 - Spicetify version 2.22.2
 - Sleek

**Comment by aphextwinning** [comment]
May be important to note this isn't an issue with the BladeRunner color scheme as I've tried using others.
Any help is appreciated!

**Comment by dndrade** [comment]
I have the same issue. I also tried changing the color of other themes but it didn't work.

- Spotify for Windows (64 bit)
- 1.2.18.999.g9b38fc27
- Spicetify v2.22.2

**Comment by darkthemer** [comment]
Are you sure that you installed the theme manually and not through the Marketplace?
The Marketplace has its own dropdown for changing color schemes.

**Comment by ccrowles** [comment]
> Are you sure that you installed the theme manually and not through the Marketplace? The Marketplace has its own dropdown for changing color schemes.

I've installed it through the marketplace but I can't find the dropdown to change colour anywhere.

**Comment by harbassan** [comment]
![Untitled](https://github.com/spicetify/spicetify-themes/assets/84175605/7b983929-3365-4824-9a86-ea73c69c16ad)

**Comment by ccrowles** [comment]
... how did I not notice that. My bad.
