### ISSUE TITLE
[text] empty space in playlist 

### ISSUE THREAD

**Issue by KnightKing2179** [spicetify/spicetify-themes#992]
empty space in playlist.
spotify version-Spotify for Windows (64 bit)
1.2.18.999.g9b38fc27
Spicetify v2.22.2
![image](https://github.com/spicetify/spicetify-themes/assets/92685947/53a662ba-fd86-41f3-bdde-4021fa5baa35)

**Comment by darkthemer** [comment]
Solution to this bug is in README.md

**Comment by afterhourss** [comment]
can you tell how to fix it?, i cant find the solution in readme

**Comment by afterhourss** [comment]
> Solution to this bug is in README.md
can you tell how to fix it?, i cant find the solution in readme

**Comment by Lol-Lap** [comment]
> can you tell how to fix it?, i cant find the solution in readme

Just edit `config-xpui.ini` file and add this
```
[Patch]
xpui.js_find_8008 = ,(\w+=)56,
xpui.js_repl_8008 = ,${1}32,
```
[README.md](https://github.com/spicetify/spicetify-themes/tree/master/text)

**Comment by afterhourss** [comment]
perfectly works thanks
