### ISSUE TITLE
[text] Weird visual bug on text

### ISSUE THREAD

**Issue by aemogie** [spicetify/spicetify-themes#993]
**Describe the bug**
I see a weird visual when I use the `text` theme, randomly. In the artist fields, sometimes I see a duplicated-ish song title. It's layered right on top of the artist field, and it gets cut off at the same size as the artist field. (Refer screenshots)
The same happens on the player controls UI as well, it's just not happening right now and I can't take a screenshot.
I tried to debug it myself, by using the developer tools, but i do not see any related HTML elements, and my CSS knowledge is just the basics, so I couldn't identify it there. Note: I found out u

**To Reproduce**
It's not entirely reproducible, but I have found that often hovering over it with my mouse sort of, reproduces it. But this method is entirely unreliable. And sometimes, hovering fixes the bug as well.

**Expected behavior**
Artist field and song title are displayed separately, with no duplicates clashing with each other. 

**Screenshots**
![image](https://github.com/spicetify/spicetify-themes/assets/54412618/e5cae00c-f19b-4954-9d54-8e16098cb518)

**Logs**
Not Applicable, I think. I didn't see any related error messages. Let me know if it is needed though, and I will attach it. (Don't want to clutter up issue)

**Specifics (please complete the following information):**
 - OS: NixOS 23.11.20230822.b85ed9d (Tapir)
 - Spotify version: 1.2.11.916.geb595a67
 - Spicetify version: 2.22.2
 - Theme name: text

**Comment by darkthemer** [comment]
I'm unable to reproduce this bug, even in Linux (Ubuntu WSL). Have you checked if it has anything to do with your modifications?

**Comment by aemogie** [comment]
I'm sorry about that, it seems the bug still exists even without using any themes. Still not sure what the cause is, but seems to be a bug with either spotify or spicetify itself.
