### ISSUE TITLE
[text] artist thumbnail issues

### ISSUE THREAD

**Issue by afterhourss** [spicetify/spicetify-themes#999]
image on artist thumbnail seems extremely zoomed in, like this :
![image](https://github.com/spicetify/spicetify-themes/assets/77962694/bd841e30-ad32-435c-bb58-093316c4d82c)

instead normally look like this (vanilla spotify) :

![image](https://github.com/spicetify/spicetify-themes/assets/77962694/b9389e12-b0ce-4548-9a56-37136ea12aa2)

 - OS: [Windows 10]
 - Spotify version [1.2.19.941.gbf202593]
 - Spicetify version [2.23.0]
 - Theme name : [text]

**Comment by harbassan** [comment]
@darkthemer
